/**
 * Canonical error codes for the SACDIA API.
 *
 * Rules:
 *   - ALL_CAPS_SNAKE format
 *   - Domain-namespaced (AUTH_, CLUB_, RBAC_, etc.)
 *   - Each code MUST have a corresponding entry in all src/i18n/{locale}/errors.json files
 *   - Phase A: generic + auth sample keys. Phase B: migrate all modules here.
 */
export enum ErrorCode {
  // ── Generic ────────────────────────────────────────────────────────────────
  GENERIC_ERROR = 'GENERIC_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // ── Database / Prisma ──────────────────────────────────────────────────────
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  RECORD_CONFLICT = 'RECORD_CONFLICT',
  RECORD_FK_VIOLATION = 'RECORD_FK_VIOLATION',
  RECORD_RELATED_NOT_FOUND = 'RECORD_RELATED_NOT_FOUND',

  // ── Auth ──────────────────────────────────────────────────────────────────
  AUTH_REFRESH_TOKEN_REQUIRED = 'AUTH_REFRESH_TOKEN_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_ROLE_NOT_FOUND = 'AUTH_USER_ROLE_NOT_FOUND',
  AUTH_REFRESH_TOKEN_LEGACY_REMOVED = 'AUTH_REFRESH_TOKEN_LEGACY_REMOVED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_PASSWORD_RESET_FAILED = 'AUTH_PASSWORD_RESET_FAILED',
  AUTH_ASSIGNMENT_NOT_FOUND = 'AUTH_ASSIGNMENT_NOT_FOUND',
  AUTH_POST_REGISTRATION_NOT_STARTED = 'AUTH_POST_REGISTRATION_NOT_STARTED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_VERIFICATION_TOKEN_INVALID = 'AUTH_EMAIL_VERIFICATION_TOKEN_INVALID',
  AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED = 'AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED',
  AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND',
  AUTH_ACCOUNT_ALREADY_DELETED = 'AUTH_ACCOUNT_ALREADY_DELETED',
  AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  AUTH_OAUTH_REDIRECT_NOT_ALLOWED = 'AUTH_OAUTH_REDIRECT_NOT_ALLOWED',
  AUTH_OAUTH_PROVIDER_INVALID = 'AUTH_OAUTH_PROVIDER_INVALID',
  AUTH_OAUTH_ONLY_AUTH_METHOD = 'AUTH_OAUTH_ONLY_AUTH_METHOD',
  AUTH_OAUTH_PROVIDER_NOT_CONNECTED = 'AUTH_OAUTH_PROVIDER_NOT_CONNECTED',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_NOT_OWNED = 'AUTH_SESSION_NOT_OWNED',
  AUTH_SESSION_IS_CURRENT = 'AUTH_SESSION_IS_CURRENT',

  // ── Annual Evidence Folders ─────────────────────────────────────────────────────────
  ANNUAL_FOLDER_OWNER_REQUIRED = 'ANNUAL_FOLDER_OWNER_REQUIRED',
  ANNUAL_FOLDER_CLUB_TYPE_NOT_FOUND = 'ANNUAL_FOLDER_CLUB_TYPE_NOT_FOUND',
  ANNUAL_FOLDER_YEAR_NOT_FOUND = 'ANNUAL_FOLDER_YEAR_NOT_FOUND',
  ANNUAL_FOLDER_TEMPLATE_NOT_FOUND = 'ANNUAL_FOLDER_TEMPLATE_NOT_FOUND',
  ANNUAL_FOLDER_TEMPLATE_SECTION_NOT_FOUND = 'ANNUAL_FOLDER_TEMPLATE_SECTION_NOT_FOUND',
  ANNUAL_FOLDER_SECTION_HAS_EVIDENCES = 'ANNUAL_FOLDER_SECTION_HAS_EVIDENCES',
  ANNUAL_FOLDER_TEMPLATE_NO_MATCH = 'ANNUAL_FOLDER_TEMPLATE_NO_MATCH',
  ANNUAL_FOLDER_TEMPLATE_RANKING_CONFIG_REQUIRED = 'ANNUAL_FOLDER_TEMPLATE_RANKING_CONFIG_REQUIRED',
  ANNUAL_FOLDER_TEMPLATE_POINTS_MISMATCH = 'ANNUAL_FOLDER_TEMPLATE_POINTS_MISMATCH',
  ANNUAL_FOLDER_TEMPLATE_LOCKED = 'ANNUAL_FOLDER_TEMPLATE_LOCKED',
  ANNUAL_FOLDER_TEMPLATE_HAS_FOLDERS = 'ANNUAL_FOLDER_TEMPLATE_HAS_FOLDERS',
  ANNUAL_FOLDER_ALREADY_EXISTS = 'ANNUAL_FOLDER_ALREADY_EXISTS',
  ANNUAL_FOLDER_NOT_FOUND = 'ANNUAL_FOLDER_NOT_FOUND',
  ANNUAL_FOLDER_ENROLLMENT_NOT_FOUND = 'ANNUAL_FOLDER_ENROLLMENT_NOT_FOUND',
  ANNUAL_FOLDER_FILE_REQUIRED = 'ANNUAL_FOLDER_FILE_REQUIRED',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_UPLOAD = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_UPLOAD',
  ANNUAL_FOLDER_SECTION_NOT_IN_TEMPLATE = 'ANNUAL_FOLDER_SECTION_NOT_IN_TEMPLATE',
  ANNUAL_FOLDER_EVIDENCE_CLUB_NOT_RESOLVED = 'ANNUAL_FOLDER_EVIDENCE_CLUB_NOT_RESOLVED',
  ANNUAL_FOLDER_EVIDENCE_ACCESS_DENIED = 'ANNUAL_FOLDER_EVIDENCE_ACCESS_DENIED',
  ANNUAL_FOLDER_FOLDER_ACCESS_DENIED = 'ANNUAL_FOLDER_FOLDER_ACCESS_DENIED',
  ANNUAL_FOLDER_EVIDENCE_TERRITORY_DENIED = 'ANNUAL_FOLDER_EVIDENCE_TERRITORY_DENIED',
  ANNUAL_FOLDER_EVIDENCE_NOT_FOUND = 'ANNUAL_FOLDER_EVIDENCE_NOT_FOUND',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_MUTATION = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_MUTATION',
  ANNUAL_FOLDER_SECTION_NO_EVIDENCE = 'ANNUAL_FOLDER_SECTION_NO_EVIDENCE',
  ANNUAL_FOLDER_SUBMISSION_CLOSED = 'ANNUAL_FOLDER_SUBMISSION_CLOSED',
  ANNUAL_FOLDER_REQUIRED_SECTIONS_PENDING = 'ANNUAL_FOLDER_REQUIRED_SECTIONS_PENDING',
  ANNUAL_FOLDER_STATUS_CONFLICT = 'ANNUAL_FOLDER_STATUS_CONFLICT',
  ANNUAL_FOLDER_CLUB_NO_PARENT = 'ANNUAL_FOLDER_CLUB_NO_PARENT',
  ANNUAL_FOLDER_CLUB_NO_LOCAL_FIELD = 'ANNUAL_FOLDER_CLUB_NO_LOCAL_FIELD',
  ANNUAL_FOLDER_CAMPOREE_CLUB_TYPE_INVALID = 'ANNUAL_FOLDER_CAMPOREE_CLUB_TYPE_INVALID',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_EVALUATE = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_EVALUATE',
  ANNUAL_FOLDER_EVAL_ROW_NOT_FOUND = 'ANNUAL_FOLDER_EVAL_ROW_NOT_FOUND',
  ANNUAL_FOLDER_SECTION_PENDING = 'ANNUAL_FOLDER_SECTION_PENDING',
  ANNUAL_FOLDER_SECTION_TERMINAL = 'ANNUAL_FOLDER_SECTION_TERMINAL',
  ANNUAL_FOLDER_EARNED_POINTS_EXCEED_MAX = 'ANNUAL_FOLDER_EARNED_POINTS_EXCEED_MAX',
  ANNUAL_FOLDER_UNION_ROLE_REQUIRED = 'ANNUAL_FOLDER_UNION_ROLE_REQUIRED',
  ANNUAL_FOLDER_UNION_CONFIRMATION_NOT_REQUIRED = 'ANNUAL_FOLDER_UNION_CONFIRMATION_NOT_REQUIRED',
  ANNUAL_FOLDER_SECTION_NOT_PREAPPROVED = 'ANNUAL_FOLDER_SECTION_NOT_PREAPPROVED',
  ANNUAL_FOLDER_SECTION_MISSING_LF_DATA = 'ANNUAL_FOLDER_SECTION_MISSING_LF_DATA',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_REOPEN = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_REOPEN',
  ANNUAL_FOLDER_SECTION_NOT_REOPENABLE = 'ANNUAL_FOLDER_SECTION_NOT_REOPENABLE',
  ANNUAL_FOLDER_RANKINGS_LOCK_CONFLICT = 'ANNUAL_FOLDER_RANKINGS_LOCK_CONFLICT',
  ANNUAL_FOLDER_ENROLLMENT_FOR_RANKING_NOT_FOUND = 'ANNUAL_FOLDER_ENROLLMENT_FOR_RANKING_NOT_FOUND',

  // ── Award Categories ───────────────────────────────────────────────────────
  AWARD_CATEGORY_POINTS_INVALID = 'AWARD_CATEGORY_POINTS_INVALID',
  AWARD_CATEGORY_CLUB_TYPE_NOT_FOUND = 'AWARD_CATEGORY_CLUB_TYPE_NOT_FOUND',
  AWARD_CATEGORY_NOT_FOUND = 'AWARD_CATEGORY_NOT_FOUND',
  AWARD_CATEGORY_SCOPE_INVALID = 'AWARD_CATEGORY_SCOPE_INVALID',
  AWARD_CATEGORY_PCT_INVALID = 'AWARD_CATEGORY_PCT_INVALID',

  // ── Camporees ──────────────────────────────────────────────────────────────
  CAMPOREE_NOT_FOUND = 'CAMPOREE_NOT_FOUND',
  CAMPOREE_NOT_ACTIVE = 'CAMPOREE_NOT_ACTIVE',
  CAMPOREE_YEAR_NOT_ACTIVE = 'CAMPOREE_YEAR_NOT_ACTIVE',
  CAMPOREE_LOCAL_FIELD_NOT_FOUND = 'CAMPOREE_LOCAL_FIELD_NOT_FOUND',
  CAMPOREE_UNION_NOT_FOUND = 'CAMPOREE_UNION_NOT_FOUND',
  CAMPOREE_LOCAL_FIELD_INVALID = 'CAMPOREE_LOCAL_FIELD_INVALID',
  CAMPOREE_MEMBER_NOT_FOUND = 'CAMPOREE_MEMBER_NOT_FOUND',
  CAMPOREE_MEMBER_ALREADY_REGISTERED = 'CAMPOREE_MEMBER_ALREADY_REGISTERED',
  CAMPOREE_USER_NOT_FOUND = 'CAMPOREE_USER_NOT_FOUND',
  CAMPOREE_INSURANCE_NOT_FOUND = 'CAMPOREE_INSURANCE_NOT_FOUND',
  CAMPOREE_INSURANCE_NOT_OWNER = 'CAMPOREE_INSURANCE_NOT_OWNER',
  CAMPOREE_INSURANCE_TYPE_INVALID = 'CAMPOREE_INSURANCE_TYPE_INVALID',
  CAMPOREE_INSURANCE_EXPIRED = 'CAMPOREE_INSURANCE_EXPIRED',
  CAMPOREE_INSURANCE_NOT_ACTIVE = 'CAMPOREE_INSURANCE_NOT_ACTIVE',
  CAMPOREE_CLUB_SECTION_NOT_FOUND = 'CAMPOREE_CLUB_SECTION_NOT_FOUND',
  CAMPOREE_CLUB_ALREADY_ENROLLED = 'CAMPOREE_CLUB_ALREADY_ENROLLED',
  CAMPOREE_CLUB_ENROLLMENT_NOT_FOUND = 'CAMPOREE_CLUB_ENROLLMENT_NOT_FOUND',
  CAMPOREE_CLUB_LOCAL_FIELD_UNKNOWN = 'CAMPOREE_CLUB_LOCAL_FIELD_UNKNOWN',
  CAMPOREE_CLUB_LOCAL_FIELD_NOT_PARTICIPATING = 'CAMPOREE_CLUB_LOCAL_FIELD_NOT_PARTICIPATING',
  CAMPOREE_PAYMENT_NOT_FOUND = 'CAMPOREE_PAYMENT_NOT_FOUND',
  CAMPOREE_UNION_CAMPOREE_NOT_FOUND = 'CAMPOREE_UNION_CAMPOREE_NOT_FOUND',
  CAMPOREE_UNION_ACCESS_DENIED = 'CAMPOREE_UNION_ACCESS_DENIED',
  CAMPOREE_LOCAL_FIELD_ACCESS_DENIED = 'CAMPOREE_LOCAL_FIELD_ACCESS_DENIED',
  CAMPOREE_CLUB_ENROLLMENT_PENDING_NOT_FOUND = 'CAMPOREE_CLUB_ENROLLMENT_PENDING_NOT_FOUND',
  CAMPOREE_MEMBER_ENROLLMENT_PENDING_NOT_FOUND = 'CAMPOREE_MEMBER_ENROLLMENT_PENDING_NOT_FOUND',
  CAMPOREE_PAYMENT_PENDING_NOT_FOUND = 'CAMPOREE_PAYMENT_PENDING_NOT_FOUND',
  CAMPOREE_PAYMENT_VOUCHER_REQUIRED = 'CAMPOREE_PAYMENT_VOUCHER_REQUIRED',
  CAMPOREE_PAYMENT_VOUCHER_TOO_LARGE = 'CAMPOREE_PAYMENT_VOUCHER_TOO_LARGE',
  CAMPOREE_PAYMENT_VOUCHER_MIME_INVALID = 'CAMPOREE_PAYMENT_VOUCHER_MIME_INVALID',
  CAMPOREE_PAYMENT_SCOPE_MISMATCH = 'CAMPOREE_PAYMENT_SCOPE_MISMATCH',

  // ── Admin — Users ──────────────────────────────────────────────────────────
  ADMIN_USER_NOT_FOUND = 'ADMIN_USER_NOT_FOUND',
  ADMIN_USER_SCOPE_MISSING = 'ADMIN_USER_SCOPE_MISSING',
  ADMIN_USER_NO_GLOBAL_PERMISSIONS = 'ADMIN_USER_NO_GLOBAL_PERMISSIONS',
  ADMIN_USER_MFA_NOT_ENABLED = 'ADMIN_USER_MFA_NOT_ENABLED',

  // ── Admin — Bulk User Upload ───────────────────────────────────────────────
  ADMIN_BULK_FILE_REQUIRED = 'ADMIN_BULK_FILE_REQUIRED',
  ADMIN_BULK_INVALID_FILE_TYPE = 'ADMIN_BULK_INVALID_FILE_TYPE',
  ADMIN_BULK_EMPTY_FILE = 'ADMIN_BULK_EMPTY_FILE',
  ADMIN_BULK_INVALID_HEADERS = 'ADMIN_BULK_INVALID_HEADERS',
  ADMIN_BULK_TOO_MANY_ROWS = 'ADMIN_BULK_TOO_MANY_ROWS',

  // ── Admin — Auth / Sessions ────────────────────────────────────────────────
  ADMIN_SESSION_NOT_FOUND = 'ADMIN_SESSION_NOT_FOUND',

  // ── Admin — Honors / Requirements ─────────────────────────────────────────
  ADMIN_HONOR_NOT_FOUND = 'ADMIN_HONOR_NOT_FOUND',
  ADMIN_HONOR_REQUIREMENT_NOT_FOUND = 'ADMIN_HONOR_REQUIREMENT_NOT_FOUND',
  ADMIN_HONOR_REQUIREMENT_WRONG_HONOR = 'ADMIN_HONOR_REQUIREMENT_WRONG_HONOR',
  ADMIN_HONOR_REQUIREMENT_CHOICE_MIN_REQUIRED = 'ADMIN_HONOR_REQUIREMENT_CHOICE_MIN_REQUIRED',

  // ── Admin — Geography ──────────────────────────────────────────────────────
  ADMIN_DIVISION_NOT_FOUND = 'ADMIN_DIVISION_NOT_FOUND',
  ADMIN_DIVISION_CODE_CONFLICT = 'ADMIN_DIVISION_CODE_CONFLICT',
  ADMIN_DIVISION_NAME_CONFLICT = 'ADMIN_DIVISION_NAME_CONFLICT',
  ADMIN_DIVISION_ABBREVIATION_CONFLICT = 'ADMIN_DIVISION_ABBREVIATION_CONFLICT',
  ADMIN_DIVISION_HAS_ACTIVE_UNIONS = 'ADMIN_DIVISION_HAS_ACTIVE_UNIONS',
  ADMIN_COUNTRY_NOT_FOUND = 'ADMIN_COUNTRY_NOT_FOUND',
  ADMIN_COUNTRY_NAME_CONFLICT = 'ADMIN_COUNTRY_NAME_CONFLICT',
  ADMIN_COUNTRY_ABBREVIATION_CONFLICT = 'ADMIN_COUNTRY_ABBREVIATION_CONFLICT',
  ADMIN_COUNTRY_HAS_ACTIVE_UNIONS = 'ADMIN_COUNTRY_HAS_ACTIVE_UNIONS',
  ADMIN_UNION_NOT_FOUND = 'ADMIN_UNION_NOT_FOUND',
  ADMIN_UNION_NAME_CONFLICT = 'ADMIN_UNION_NAME_CONFLICT',
  ADMIN_UNION_ABBREVIATION_CONFLICT = 'ADMIN_UNION_ABBREVIATION_CONFLICT',
  ADMIN_UNION_HAS_ACTIVE_LOCAL_FIELDS = 'ADMIN_UNION_HAS_ACTIVE_LOCAL_FIELDS',
  ADMIN_LOCAL_FIELD_NOT_FOUND = 'ADMIN_LOCAL_FIELD_NOT_FOUND',
  ADMIN_LOCAL_FIELD_NAME_CONFLICT = 'ADMIN_LOCAL_FIELD_NAME_CONFLICT',
  ADMIN_LOCAL_FIELD_ABBREVIATION_CONFLICT = 'ADMIN_LOCAL_FIELD_ABBREVIATION_CONFLICT',
  ADMIN_LOCAL_FIELD_HAS_ACTIVE_DISTRICTS = 'ADMIN_LOCAL_FIELD_HAS_ACTIVE_DISTRICTS',
  ADMIN_DISTRICT_NOT_FOUND = 'ADMIN_DISTRICT_NOT_FOUND',
  ADMIN_DISTRICT_NAME_CONFLICT = 'ADMIN_DISTRICT_NAME_CONFLICT',
  ADMIN_DISTRICT_HAS_ACTIVE_CHURCHES = 'ADMIN_DISTRICT_HAS_ACTIVE_CHURCHES',
  ADMIN_CHURCH_NOT_FOUND = 'ADMIN_CHURCH_NOT_FOUND',
  ADMIN_CHURCH_NAME_CONFLICT = 'ADMIN_CHURCH_NAME_CONFLICT',

  // ── Institutional Hierarchy ────────────────────────────────────────────────
  HIERARCHY_COUNTRY_DIVISION_AMBIGUOUS = 'HIERARCHY_COUNTRY_DIVISION_AMBIGUOUS',
  HIERARCHY_CONTEXT_NOT_FOUND = 'HIERARCHY_CONTEXT_NOT_FOUND',
  HIERARCHY_HISTORICAL_SCOPE_DENIED = 'HIERARCHY_HISTORICAL_SCOPE_DENIED',

  // ── Admin — Reference Catalogs ─────────────────────────────────────────────
  ADMIN_ACTIVITY_TYPE_NOT_FOUND = 'ADMIN_ACTIVITY_TYPE_NOT_FOUND',
  ADMIN_ACTIVITY_TYPE_NAME_CONFLICT = 'ADMIN_ACTIVITY_TYPE_NAME_CONFLICT',
  ADMIN_ACTIVITY_TYPE_CODE_CONFLICT = 'ADMIN_ACTIVITY_TYPE_CODE_CONFLICT',
  ADMIN_ACTIVITY_TYPE_IN_USE = 'ADMIN_ACTIVITY_TYPE_IN_USE',
  ADMIN_RELATIONSHIP_TYPE_NOT_FOUND = 'ADMIN_RELATIONSHIP_TYPE_NOT_FOUND',
  ADMIN_RELATIONSHIP_TYPE_NAME_CONFLICT = 'ADMIN_RELATIONSHIP_TYPE_NAME_CONFLICT',
  ADMIN_RELATIONSHIP_TYPE_IN_USE = 'ADMIN_RELATIONSHIP_TYPE_IN_USE',
  ADMIN_ALLERGY_NOT_FOUND = 'ADMIN_ALLERGY_NOT_FOUND',
  ADMIN_ALLERGY_NAME_CONFLICT = 'ADMIN_ALLERGY_NAME_CONFLICT',
  ADMIN_ALLERGY_IN_USE = 'ADMIN_ALLERGY_IN_USE',
  ADMIN_DISEASE_NOT_FOUND = 'ADMIN_DISEASE_NOT_FOUND',
  ADMIN_DISEASE_NAME_CONFLICT = 'ADMIN_DISEASE_NAME_CONFLICT',
  ADMIN_DISEASE_IN_USE = 'ADMIN_DISEASE_IN_USE',
  ADMIN_MEDICINE_NOT_FOUND = 'ADMIN_MEDICINE_NOT_FOUND',
  ADMIN_MEDICINE_NAME_CONFLICT = 'ADMIN_MEDICINE_NAME_CONFLICT',
  ADMIN_MEDICINE_IN_USE = 'ADMIN_MEDICINE_IN_USE',
  ADMIN_ECCLESIASTICAL_YEAR_NOT_FOUND = 'ADMIN_ECCLESIASTICAL_YEAR_NOT_FOUND',
  ADMIN_ECCLESIASTICAL_YEAR_DATE_INVALID = 'ADMIN_ECCLESIASTICAL_YEAR_DATE_INVALID',
  ADMIN_ECCLESIASTICAL_YEAR_HAS_ACTIVE_ASSIGNMENTS = 'ADMIN_ECCLESIASTICAL_YEAR_HAS_ACTIVE_ASSIGNMENTS',
  ADMIN_CLUB_TYPE_NOT_FOUND = 'ADMIN_CLUB_TYPE_NOT_FOUND',
  ADMIN_CLUB_TYPE_NAME_CONFLICT = 'ADMIN_CLUB_TYPE_NAME_CONFLICT',
  ADMIN_CLUB_TYPE_IN_USE = 'ADMIN_CLUB_TYPE_IN_USE',
  ADMIN_CLUB_IDEAL_NOT_FOUND = 'ADMIN_CLUB_IDEAL_NOT_FOUND',
  ADMIN_HONOR_CATEGORY_NOT_FOUND = 'ADMIN_HONOR_CATEGORY_NOT_FOUND',
  ADMIN_HONOR_CATEGORY_NAME_CONFLICT = 'ADMIN_HONOR_CATEGORY_NAME_CONFLICT',
  ADMIN_HONOR_CATEGORY_IN_USE = 'ADMIN_HONOR_CATEGORY_IN_USE',

  // ── Phase E — i18n catalog CRUD ────────────────────────────────────────────
  ADMIN_CLASS_NOT_FOUND = 'ADMIN_CLASS_NOT_FOUND',
  ADMIN_CLASS_NAME_CONFLICT = 'ADMIN_CLASS_NAME_CONFLICT',
  ADMIN_CLASS_MODULE_NOT_FOUND = 'ADMIN_CLASS_MODULE_NOT_FOUND',
  ADMIN_CLASS_MODULE_NAME_CONFLICT = 'ADMIN_CLASS_MODULE_NAME_CONFLICT',
  ADMIN_CLASS_SECTION_NOT_FOUND = 'ADMIN_CLASS_SECTION_NOT_FOUND',
  ADMIN_CLASS_SECTION_NAME_CONFLICT = 'ADMIN_CLASS_SECTION_NAME_CONFLICT',
  ADMIN_FOLDER_NOT_FOUND = 'ADMIN_FOLDER_NOT_FOUND',
  ADMIN_FOLDER_NAME_CONFLICT = 'ADMIN_FOLDER_NAME_CONFLICT',
  ADMIN_FOLDER_MODULE_NOT_FOUND = 'ADMIN_FOLDER_MODULE_NOT_FOUND',
  ADMIN_FOLDER_MODULE_NAME_CONFLICT = 'ADMIN_FOLDER_MODULE_NAME_CONFLICT',
  ADMIN_FOLDER_SECTION_NOT_FOUND = 'ADMIN_FOLDER_SECTION_NOT_FOUND',
  ADMIN_FOLDER_SECTION_NAME_CONFLICT = 'ADMIN_FOLDER_SECTION_NAME_CONFLICT',
  ADMIN_FINANCE_CATEGORY_NOT_FOUND = 'ADMIN_FINANCE_CATEGORY_NOT_FOUND',
  ADMIN_FINANCE_CATEGORY_NAME_CONFLICT = 'ADMIN_FINANCE_CATEGORY_NAME_CONFLICT',
  ADMIN_INVENTORY_CATEGORY_NOT_FOUND = 'ADMIN_INVENTORY_CATEGORY_NOT_FOUND',
  ADMIN_INVENTORY_CATEGORY_NAME_CONFLICT = 'ADMIN_INVENTORY_CATEGORY_NAME_CONFLICT',
  ADMIN_HONOR_NOT_FOUND_CATALOG = 'ADMIN_HONOR_NOT_FOUND_CATALOG',
  ADMIN_HONOR_NAME_CONFLICT = 'ADMIN_HONOR_NAME_CONFLICT',
  ADMIN_MASTER_HONOR_NOT_FOUND = 'ADMIN_MASTER_HONOR_NOT_FOUND',
  ADMIN_MASTER_HONOR_NAME_CONFLICT = 'ADMIN_MASTER_HONOR_NAME_CONFLICT',

  // ── RBAC ──────────────────────────────────────────────────────────────────
  RBAC_PERMISSION_NOT_FOUND = 'RBAC_PERMISSION_NOT_FOUND',
  RBAC_PERMISSION_NAME_CONFLICT = 'RBAC_PERMISSION_NAME_CONFLICT',
  RBAC_ROLE_NOT_FOUND = 'RBAC_ROLE_NOT_FOUND',
  RBAC_ROLE_NAME_CONFLICT = 'RBAC_ROLE_NAME_CONFLICT',
  RBAC_ROLE_NAME_RESERVED = 'RBAC_ROLE_NAME_RESERVED',
  RBAC_ROLE_NAME_IMMUTABLE = 'RBAC_ROLE_NAME_IMMUTABLE',
  RBAC_ROLE_PROTECTED = 'RBAC_ROLE_PROTECTED',
  RBAC_ROLE_HAS_ASSIGNMENTS = 'RBAC_ROLE_HAS_ASSIGNMENTS',
  RBAC_PERMISSIONS_NOT_FOUND = 'RBAC_PERMISSIONS_NOT_FOUND',
  RBAC_ROLE_PERMISSION_NOT_FOUND = 'RBAC_ROLE_PERMISSION_NOT_FOUND',
  RBAC_USER_NOT_FOUND = 'RBAC_USER_NOT_FOUND',
  RBAC_USER_PERMISSION_ALREADY_ASSIGNED = 'RBAC_USER_PERMISSION_ALREADY_ASSIGNED',
  RBAC_USER_PERMISSION_NOT_FOUND = 'RBAC_USER_PERMISSION_NOT_FOUND',
  RBAC_USER_ROLE_ALREADY_ASSIGNED = 'RBAC_USER_ROLE_ALREADY_ASSIGNED',
  RBAC_USER_ROLE_NOT_FOUND = 'RBAC_USER_ROLE_NOT_FOUND',
  RBAC_SUPER_ADMIN_ALREADY_EXISTS = 'RBAC_SUPER_ADMIN_ALREADY_EXISTS',
  RBAC_SUPER_ADMIN_ROLE_NOT_FOUND = 'RBAC_SUPER_ADMIN_ROLE_NOT_FOUND',

  // ── Evidence Review ────────────────────────────────────────────────────────
  EVIDENCE_REVIEW_TYPE_INVALID = 'EVIDENCE_REVIEW_TYPE_INVALID',
  EVIDENCE_REVIEW_FOLDER_RECORD_NOT_FOUND = 'EVIDENCE_REVIEW_FOLDER_RECORD_NOT_FOUND',
  EVIDENCE_REVIEW_CLASS_RECORD_NOT_FOUND = 'EVIDENCE_REVIEW_CLASS_RECORD_NOT_FOUND',
  EVIDENCE_REVIEW_RECORD_NOT_PENDING = 'EVIDENCE_REVIEW_RECORD_NOT_PENDING',
  EVIDENCE_REVIEW_RECORD_ALREADY_REJECTED = 'EVIDENCE_REVIEW_RECORD_ALREADY_REJECTED',
  EVIDENCE_REVIEW_RECORD_ALREADY_VALIDATED = 'EVIDENCE_REVIEW_RECORD_ALREADY_VALIDATED',
  EVIDENCE_REVIEW_USER_HONOR_NOT_FOUND = 'EVIDENCE_REVIEW_USER_HONOR_NOT_FOUND',
  EVIDENCE_REVIEW_USER_HONOR_NOT_PENDING = 'EVIDENCE_REVIEW_USER_HONOR_NOT_PENDING',
  EVIDENCE_REVIEW_USER_HONOR_ALREADY_REJECTED = 'EVIDENCE_REVIEW_USER_HONOR_ALREADY_REJECTED',
  EVIDENCE_REVIEW_USER_HONOR_ALREADY_APPROVED = 'EVIDENCE_REVIEW_USER_HONOR_ALREADY_APPROVED',

  // ── Resources ──────────────────────────────────────────────────────────────
  RESOURCE_SCOPE_SYSTEM_NO_SCOPE_ID = 'RESOURCE_SCOPE_SYSTEM_NO_SCOPE_ID',
  RESOURCE_SCOPE_NON_SYSTEM_MISSING_SCOPE_ID = 'RESOURCE_SCOPE_NON_SYSTEM_MISSING_SCOPE_ID',
  RESOURCE_CATEGORY_NOT_FOUND = 'RESOURCE_CATEGORY_NOT_FOUND',
  RESOURCE_CATEGORY_IN_USE = 'RESOURCE_CATEGORY_IN_USE',
  RESOURCE_CLUB_TYPE_NOT_FOUND = 'RESOURCE_CLUB_TYPE_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_NO_FILE = 'RESOURCE_NO_FILE',
  RESOURCE_SCOPE_ACCESS_DENIED_SYSTEM = 'RESOURCE_SCOPE_ACCESS_DENIED_SYSTEM',
  RESOURCE_SCOPE_ACCESS_DENIED_DIVISION = 'RESOURCE_SCOPE_ACCESS_DENIED_DIVISION',
  RESOURCE_SCOPE_ACCESS_DENIED_UNION = 'RESOURCE_SCOPE_ACCESS_DENIED_UNION',
  RESOURCE_SCOPE_ACCESS_DENIED_LOCAL_FIELD = 'RESOURCE_SCOPE_ACCESS_DENIED_LOCAL_FIELD',
  RESOURCE_SCOPE_LEVEL_INVALID = 'RESOURCE_SCOPE_LEVEL_INVALID',
  RESOURCE_FILE_CONTENT_MISMATCH = 'RESOURCE_FILE_CONTENT_MISMATCH',
  RESOURCE_FILE_NOT_REQUIRED = 'RESOURCE_FILE_NOT_REQUIRED',
  RESOURCE_FILE_REQUIRED = 'RESOURCE_FILE_REQUIRED',
  RESOURCE_FILE_TOO_LARGE = 'RESOURCE_FILE_TOO_LARGE',
  RESOURCE_FILE_TYPE_INVALID = 'RESOURCE_FILE_TYPE_INVALID',
  RESOURCE_FILE_MIME_INVALID = 'RESOURCE_FILE_MIME_INVALID',

  // ── Honors ─────────────────────────────────────────────────────────────────
  HONOR_NOT_FOUND = 'HONOR_NOT_FOUND',
  HONOR_USER_ALREADY_IN_PROGRESS = 'HONOR_USER_ALREADY_IN_PROGRESS',
  HONOR_ACTIVE_SECTION_REQUIRED = 'HONOR_ACTIVE_SECTION_REQUIRED',
  HONOR_CLUB_TYPE_NOT_ALLOWED = 'HONOR_CLUB_TYPE_NOT_ALLOWED',
  HONOR_BULK_DUPLICATE_IDS = 'HONOR_BULK_DUPLICATE_IDS',
  HONOR_BULK_NOT_FOUND = 'HONOR_BULK_NOT_FOUND',
  HONOR_FILE_REQUIRED = 'HONOR_FILE_REQUIRED',
  HONOR_USER_HONOR_NOT_FOUND = 'HONOR_USER_HONOR_NOT_FOUND',
  HONOR_FILE_UPLOAD_FAILED = 'HONOR_FILE_UPLOAD_FAILED',
  HONOR_FILE_INVALID_FORMAT = 'HONOR_FILE_INVALID_FORMAT',
  HONOR_FILE_TOO_LARGE = 'HONOR_FILE_TOO_LARGE',
  HONOR_USER_NOT_ENROLLED = 'HONOR_USER_NOT_ENROLLED',
  HONOR_REQUIREMENT_NOT_IN_HONOR = 'HONOR_REQUIREMENT_NOT_IN_HONOR',
  HONOR_EVIDENCE_MAX_REACHED = 'HONOR_EVIDENCE_MAX_REACHED',
  HONOR_EVIDENCE_NOT_FOUND = 'HONOR_EVIDENCE_NOT_FOUND',

  // ── Investiture ────────────────────────────────────────────────────────────
  INVESTITURE_ENROLLMENT_NOT_FOUND = 'INVESTITURE_ENROLLMENT_NOT_FOUND',
  INVESTITURE_INVALID_STATE_TRANSITION = 'INVESTITURE_INVALID_STATE_TRANSITION',
  INVESTITURE_ALREADY_INVESTIDO = 'INVESTITURE_ALREADY_INVESTIDO',
  INVESTITURE_REJECT_COMMENTS_REQUIRED = 'INVESTITURE_REJECT_COMMENTS_REQUIRED',
  INVESTITURE_ACCESS_DENIED = 'INVESTITURE_ACCESS_DENIED',
  INVESTITURE_FIELD_APPROVE_REQUIRES_ADMIN = 'INVESTITURE_FIELD_APPROVE_REQUIRES_ADMIN',
  INVESTITURE_CONFIG_NOT_FOUND = 'INVESTITURE_CONFIG_NOT_FOUND',
  INVESTITURE_CONFIG_DUPLICATE = 'INVESTITURE_CONFIG_DUPLICATE',
  INVESTITURE_CONCURRENT_UPDATE = 'INVESTITURE_CONCURRENT_UPDATE',
  INVESTITURE_DURATION_MIN_NOT_MET = 'INVESTITURE_DURATION_MIN_NOT_MET',
  INVESTITURE_DURATION_EXPIRED = 'INVESTITURE_DURATION_EXPIRED',

  // ── Activities ─────────────────────────────────────────────────────────────
  ACTIVITY_CLUB_NOT_FOUND = 'ACTIVITY_CLUB_NOT_FOUND',
  ACTIVITY_NOT_FOUND = 'ACTIVITY_NOT_FOUND',
  ACTIVITY_SECTION_ID_REQUIRED = 'ACTIVITY_SECTION_ID_REQUIRED',
  ACTIVITY_SECTION_DUPLICATE_IDS = 'ACTIVITY_SECTION_DUPLICATE_IDS',
  ACTIVITY_SECTION_OWNER_NOT_IN_LIST = 'ACTIVITY_SECTION_OWNER_NOT_IN_LIST',
  ACTIVITY_SECTION_CLUB_TYPE_MISMATCH = 'ACTIVITY_SECTION_CLUB_TYPE_MISMATCH',
  ACTIVITY_NO_OWNER_SECTION = 'ACTIVITY_NO_OWNER_SECTION',
  ACTIVITY_SECTION_NOT_FOUND = 'ACTIVITY_SECTION_NOT_FOUND',
  ACTIVITY_SECTION_WRONG_CLUB = 'ACTIVITY_SECTION_WRONG_CLUB',
  ACTIVITY_IMAGE_INVALID_FORMAT = 'ACTIVITY_IMAGE_INVALID_FORMAT',
  ACTIVITY_IMAGE_TOO_LARGE = 'ACTIVITY_IMAGE_TOO_LARGE',
  ACTIVITY_IMAGE_UPLOAD_FAILED = 'ACTIVITY_IMAGE_UPLOAD_FAILED',
  ACTIVITY_IMAGE_UPDATE_FAILED = 'ACTIVITY_IMAGE_UPDATE_FAILED',

  // ── Users ──────────────────────────────────────────────────────────────────
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_COUNTRY_INVALID = 'USER_COUNTRY_INVALID',
  USER_UNION_INVALID = 'USER_UNION_INVALID',
  USER_LOCAL_FIELD_INVALID = 'USER_LOCAL_FIELD_INVALID',
  USER_UNION_COUNTRY_MISMATCH = 'USER_UNION_COUNTRY_MISMATCH',
  USER_LOCAL_FIELD_UNION_MISMATCH = 'USER_LOCAL_FIELD_UNION_MISMATCH',
  USER_ALLERGY_INVALID = 'USER_ALLERGY_INVALID',
  USER_DISEASE_INVALID = 'USER_DISEASE_INVALID',
  USER_MEDICINE_INVALID = 'USER_MEDICINE_INVALID',
  USER_BAPTISM_DATE_CONFLICT = 'USER_BAPTISM_DATE_CONFLICT',
  USER_PROFILE_GEOGRAPHY_READ_ONLY = 'USER_PROFILE_GEOGRAPHY_READ_ONLY',
  USER_ALLERGY_NOT_IN_PROFILE = 'USER_ALLERGY_NOT_IN_PROFILE',
  USER_DISEASE_NOT_IN_PROFILE = 'USER_DISEASE_NOT_IN_PROFILE',
  USER_MEDICINE_NOT_IN_PROFILE = 'USER_MEDICINE_NOT_IN_PROFILE',
  USER_IMAGE_INVALID_FORMAT = 'USER_IMAGE_INVALID_FORMAT',
  USER_IMAGE_TOO_LARGE = 'USER_IMAGE_TOO_LARGE',
  USER_IMAGE_UPLOAD_FAILED = 'USER_IMAGE_UPLOAD_FAILED',
  USER_IMAGE_UPDATE_FAILED = 'USER_IMAGE_UPDATE_FAILED',
  USER_NO_PROFILE_PICTURE = 'USER_NO_PROFILE_PICTURE',
  USER_IMAGE_DELETE_FAILED = 'USER_IMAGE_DELETE_FAILED',

  // ── Folders ────────────────────────────────────────────────────────────────
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',
  FOLDER_ALREADY_ENROLLED = 'FOLDER_ALREADY_ENROLLED',
  FOLDER_USER_NO_CLUB_TYPE = 'FOLDER_USER_NO_CLUB_TYPE',
  FOLDER_ASSIGNMENT_NOT_FOUND = 'FOLDER_ASSIGNMENT_NOT_FOUND',
  FOLDER_USER_NOT_FOUND = 'FOLDER_USER_NOT_FOUND',
  FOLDER_SECTION_INVALID = 'FOLDER_SECTION_INVALID',
  FOLDER_POINTS_EXCEED_MAX = 'FOLDER_POINTS_EXCEED_MAX',
  FOLDER_EVIDENCE_SECTION_NOT_FOUND = 'FOLDER_EVIDENCE_SECTION_NOT_FOUND',
  FOLDER_EVIDENCE_SECTION_NOT_PENDING = 'FOLDER_EVIDENCE_SECTION_NOT_PENDING',
  FOLDER_EVIDENCE_FILE_REQUIRED = 'FOLDER_EVIDENCE_FILE_REQUIRED',
  FOLDER_EVIDENCE_NO_FILES_FOR_SUBMIT = 'FOLDER_EVIDENCE_NO_FILES_FOR_SUBMIT',
  FOLDER_EVIDENCE_FILE_NOT_FOUND = 'FOLDER_EVIDENCE_FILE_NOT_FOUND',
  FOLDER_EVIDENCE_FOLDER_NOT_FOUND = 'FOLDER_EVIDENCE_FOLDER_NOT_FOUND',

  // ── Classes ────────────────────────────────────────────────────────────────
  CLASS_ENROLLMENT_NOT_FOUND = 'CLASS_ENROLLMENT_NOT_FOUND',
  CLASS_ACTIVE_YEAR_NOT_FOUND = 'CLASS_ACTIVE_YEAR_NOT_FOUND',
  CLASS_ENROLLMENT_AMBIGUOUS = 'CLASS_ENROLLMENT_AMBIGUOUS',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',
  CLASS_GM_INVESTITURE_REQUIRED = 'CLASS_GM_INVESTITURE_REQUIRED',
  CLASS_MAX_AVENTU_CONQUIS_ACTIVE = 'CLASS_MAX_AVENTU_CONQUIS_ACTIVE',
  CLASS_MAX_GM_ACTIVE = 'CLASS_MAX_GM_ACTIVE',
  CLASS_ALREADY_ENROLLED = 'CLASS_ALREADY_ENROLLED',
  CLASS_FILE_REQUIRED = 'CLASS_FILE_REQUIRED',
  CLASS_FILE_INVALID_TYPE = 'CLASS_FILE_INVALID_TYPE',
  CLASS_SECTION_NOT_FOUND = 'CLASS_SECTION_NOT_FOUND',
  CLASS_SECTION_PROGRESS_NOT_FOUND = 'CLASS_SECTION_PROGRESS_NOT_FOUND',
  CLASS_SECTION_ALREADY_SUBMITTED = 'CLASS_SECTION_ALREADY_SUBMITTED',
  CLASS_SECTION_NO_EVIDENCE = 'CLASS_SECTION_NO_EVIDENCE',
  CLASS_EVIDENCE_FILE_NOT_FOUND = 'CLASS_EVIDENCE_FILE_NOT_FOUND',
  CLASS_LEVEL_TOO_HIGH = 'CLASS_LEVEL_TOO_HIGH',
  CLASS_NOT_AVAILABLE_FOR_YEAR = 'CLASS_NOT_AVAILABLE_FOR_YEAR',
  CLASS_COUNSELOR_ASSIGNMENT_NOT_FOUND = 'CLASS_COUNSELOR_ASSIGNMENT_NOT_FOUND',
  CLASS_COUNSELOR_SECTION_NOT_FOUND = 'CLASS_COUNSELOR_SECTION_NOT_FOUND',
  CLASS_COUNSELOR_CLASS_NOT_FOUND = 'CLASS_COUNSELOR_CLASS_NOT_FOUND',
  CLASS_COUNSELOR_CLASS_TYPE_MISMATCH = 'CLASS_COUNSELOR_CLASS_TYPE_MISMATCH',
  CLASS_COUNSELOR_ROLE_ASSIGNMENT_REQUIRED = 'CLASS_COUNSELOR_ROLE_ASSIGNMENT_REQUIRED',
  CLASS_COUNSELOR_ROLE_NOT_ASSIGNABLE = 'CLASS_COUNSELOR_ROLE_NOT_ASSIGNABLE',
  CLASS_COUNSELOR_ASSIGNMENT_DUPLICATE = 'CLASS_COUNSELOR_ASSIGNMENT_DUPLICATE',
  CLASS_COUNSELOR_CLASS_LIMIT_REACHED = 'CLASS_COUNSELOR_CLASS_LIMIT_REACHED',
  CLASS_COUNSELOR_PRIMARY_EXISTS = 'CLASS_COUNSELOR_PRIMARY_EXISTS',
  CLASS_COUNSELOR_EXCEPTION_REQUIRED = 'CLASS_COUNSELOR_EXCEPTION_REQUIRED',
  CLASS_COUNSELOR_USER_LIMIT_REACHED = 'CLASS_COUNSELOR_USER_LIMIT_REACHED',
  CLASS_COUNSELOR_INVALID_RESPONSIBILITY_TYPE = 'CLASS_COUNSELOR_INVALID_RESPONSIBILITY_TYPE',
  CLASS_COUNSELOR_GUIDE_MAJOR_REQUIRED = 'CLASS_COUNSELOR_GUIDE_MAJOR_REQUIRED',

  // ── Units ──────────────────────────────────────────────────────────────────
  UNIT_CLUB_NOT_FOUND = 'UNIT_CLUB_NOT_FOUND',
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  UNIT_SECTION_NOT_FOUND = 'UNIT_SECTION_NOT_FOUND',
  UNIT_SECTION_WRONG_CLUB = 'UNIT_SECTION_WRONG_CLUB',
  UNIT_SECTION_TYPE_MISMATCH = 'UNIT_SECTION_TYPE_MISMATCH',
  UNIT_USER_NOT_FOUND = 'UNIT_USER_NOT_FOUND',
  UNIT_USER_NOT_IN_SECTION = 'UNIT_USER_NOT_IN_SECTION',
  UNIT_MEMBER_ALREADY_IN_SECTION = 'UNIT_MEMBER_ALREADY_IN_SECTION',
  UNIT_MEMBER_ALREADY_IN_UNIT = 'UNIT_MEMBER_ALREADY_IN_UNIT',
  UNIT_MEMBER_NOT_FOUND = 'UNIT_MEMBER_NOT_FOUND',
  UNIT_MEMBER_NOT_ACTIVE = 'UNIT_MEMBER_NOT_ACTIVE',
  UNIT_WEEKLY_RECORD_DUPLICATE = 'UNIT_WEEKLY_RECORD_DUPLICATE',
  UNIT_WEEKLY_RECORD_DUPLICATE_USER = 'UNIT_WEEKLY_RECORD_DUPLICATE_USER',
  UNIT_WEEKLY_RECORD_NOT_FOUND = 'UNIT_WEEKLY_RECORD_NOT_FOUND',
  UNIT_WEEKLY_RECORD_WRONG_UNIT = 'UNIT_WEEKLY_RECORD_WRONG_UNIT',
  UNIT_WEEKLY_RECORD_PERIOD_CLOSED = 'UNIT_WEEKLY_RECORD_PERIOD_CLOSED',
  UNIT_SCORING_CATEGORY_INVALID = 'UNIT_SCORING_CATEGORY_INVALID',
  UNIT_SCORING_POINTS_EXCEED_MAX = 'UNIT_SCORING_POINTS_EXCEED_MAX',
  UNIT_SCORING_BOOLEAN_POINTS_INVALID = 'UNIT_SCORING_BOOLEAN_POINTS_INVALID',

  // ── Requests ───────────────────────────────────────────────────────────────
  REQUEST_TRANSFER_SAME_SECTION = 'REQUEST_TRANSFER_SAME_SECTION',
  REQUEST_TRANSFER_USER_NOT_IN_SECTION = 'REQUEST_TRANSFER_USER_NOT_IN_SECTION',
  REQUEST_TRANSFER_SECTION_NOT_FOUND = 'REQUEST_TRANSFER_SECTION_NOT_FOUND',
  REQUEST_TRANSFER_TYPE_MISMATCH = 'REQUEST_TRANSFER_TYPE_MISMATCH',
  REQUEST_TRANSFER_PENDING_EXISTS = 'REQUEST_TRANSFER_PENDING_EXISTS',
  REQUEST_TRANSFER_NOT_FOUND = 'REQUEST_TRANSFER_NOT_FOUND',
  REQUEST_TRANSFER_ALREADY_REVIEWED = 'REQUEST_TRANSFER_ALREADY_REVIEWED',
  REQUEST_SECTION_NOT_FOUND = 'REQUEST_SECTION_NOT_FOUND',
  REQUEST_USER_NOT_FOUND = 'REQUEST_USER_NOT_FOUND',
  REQUEST_ROLE_NOT_FOUND = 'REQUEST_ROLE_NOT_FOUND',
  REQUEST_ASSIGNMENT_PENDING_EXISTS = 'REQUEST_ASSIGNMENT_PENDING_EXISTS',
  REQUEST_ASSIGNMENT_NOT_FOUND = 'REQUEST_ASSIGNMENT_NOT_FOUND',
  REQUEST_ASSIGNMENT_ALREADY_REVIEWED = 'REQUEST_ASSIGNMENT_ALREADY_REVIEWED',
  REQUEST_ROLE_SLOT_LIMIT_REACHED = 'REQUEST_ROLE_SLOT_LIMIT_REACHED',
  REQUEST_NO_ACTIVE_YEAR = 'REQUEST_NO_ACTIVE_YEAR',

  // ── Scoring Categories ─────────────────────────────────────────────────────
  SCORING_CATEGORY_NOT_FOUND = 'SCORING_CATEGORY_NOT_FOUND',
  SCORING_CATEGORY_WRONG_LEVEL = 'SCORING_CATEGORY_WRONG_LEVEL',
  SCORING_CATEGORY_UNION_FORBIDDEN = 'SCORING_CATEGORY_UNION_FORBIDDEN',
  SCORING_CATEGORY_LOCAL_FIELD_FORBIDDEN = 'SCORING_CATEGORY_LOCAL_FIELD_FORBIDDEN',
  SCORING_CATEGORY_MAX_POINTS_EXCEEDS_CAP = 'SCORING_CATEGORY_MAX_POINTS_EXCEEDS_CAP',
  SCORING_DIVISION_NOT_FOUND = 'SCORING_DIVISION_NOT_FOUND',
  SCORING_UNION_NOT_FOUND = 'SCORING_UNION_NOT_FOUND',
  SCORING_LOCAL_FIELD_NOT_FOUND = 'SCORING_LOCAL_FIELD_NOT_FOUND',

  // ── Monthly Reports ────────────────────────────────────────────────────────
  MONTHLY_REPORT_ENROLLMENT_NOT_FOUND = 'MONTHLY_REPORT_ENROLLMENT_NOT_FOUND',
  MONTHLY_REPORT_NOT_FOUND = 'MONTHLY_REPORT_NOT_FOUND',
  MONTHLY_REPORT_NOT_DRAFT = 'MONTHLY_REPORT_NOT_DRAFT',
  MONTHLY_REPORT_NOT_GENERATED = 'MONTHLY_REPORT_NOT_GENERATED',
  MONTHLY_REPORT_INVALID_MONTH = 'MONTHLY_REPORT_INVALID_MONTH',
  MONTHLY_REPORT_INVALID_YEAR = 'MONTHLY_REPORT_INVALID_YEAR',

  // ── Quarterly Reports ──────────────────────────────────────────────────────
  QUARTERLY_REPORT_NOT_FOUND = 'QUARTERLY_REPORT_NOT_FOUND',
  QUARTERLY_REPORT_NOT_DRAFT = 'QUARTERLY_REPORT_NOT_DRAFT',
  QUARTERLY_REPORT_NOT_FINALIZED = 'QUARTERLY_REPORT_NOT_FINALIZED',
  QUARTERLY_REPORT_CLUB_NOT_FOUND = 'QUARTERLY_REPORT_CLUB_NOT_FOUND',
  QUARTERLY_REPORT_INVALID_QUARTER = 'QUARTERLY_REPORT_INVALID_QUARTER',
  QUARTERLY_REPORT_INVALID_YEAR = 'QUARTERLY_REPORT_INVALID_YEAR',
  QUARTERLY_REPORT_PDF_NOT_READY = 'QUARTERLY_REPORT_PDF_NOT_READY',

  // ── Annual Reports ─────────────────────────────────────────────────────────
  ANNUAL_REPORT_NOT_FOUND = 'ANNUAL_REPORT_NOT_FOUND',
  ANNUAL_REPORT_NOT_DRAFT = 'ANNUAL_REPORT_NOT_DRAFT',
  ANNUAL_REPORT_NOT_FINALIZED = 'ANNUAL_REPORT_NOT_FINALIZED',
  ANNUAL_REPORT_CLUB_NOT_FOUND = 'ANNUAL_REPORT_CLUB_NOT_FOUND',
  ANNUAL_REPORT_YEAR_NOT_FOUND = 'ANNUAL_REPORT_YEAR_NOT_FOUND',
  ANNUAL_REPORT_PDF_NOT_READY = 'ANNUAL_REPORT_PDF_NOT_READY',

  // ── Validation ─────────────────────────────────────────────────────────────
  VALIDATION_ENROLLMENT_NOT_FOUND = 'VALIDATION_ENROLLMENT_NOT_FOUND',
  VALIDATION_ENROLLMENT_NOT_OWNED = 'VALIDATION_ENROLLMENT_NOT_OWNED',
  VALIDATION_ENROLLMENT_NOT_IN_PROGRESS = 'VALIDATION_ENROLLMENT_NOT_IN_PROGRESS',
  VALIDATION_ENROLLMENT_NOT_SUBMITTED = 'VALIDATION_ENROLLMENT_NOT_SUBMITTED',
  VALIDATION_USER_HONOR_NOT_FOUND = 'VALIDATION_USER_HONOR_NOT_FOUND',
  VALIDATION_HONOR_NOT_OWNED = 'VALIDATION_HONOR_NOT_OWNED',
  VALIDATION_HONOR_ALREADY_VALIDATED = 'VALIDATION_HONOR_ALREADY_VALIDATED',
  VALIDATION_HONOR_ALREADY_PENDING = 'VALIDATION_HONOR_ALREADY_PENDING',
  VALIDATION_HONOR_INVALID_STATUS = 'VALIDATION_HONOR_INVALID_STATUS',
  VALIDATION_HONOR_INACTIVE = 'VALIDATION_HONOR_INACTIVE',
  VALIDATION_HONOR_COMPLETION_MODE_REQUIRED = 'VALIDATION_HONOR_COMPLETION_MODE_REQUIRED',
  VALIDATION_HONOR_MISSING_EVIDENCE = 'VALIDATION_HONOR_MISSING_EVIDENCE',
  VALIDATION_HONOR_REQUIREMENTS_INCOMPLETE = 'VALIDATION_HONOR_REQUIREMENTS_INCOMPLETE',
  VALIDATION_HONOR_NO_CHANGES_AFTER_REJECTION = 'VALIDATION_HONOR_NO_CHANGES_AFTER_REJECTION',
  VALIDATION_HONOR_NOT_PENDING = 'VALIDATION_HONOR_NOT_PENDING',
  VALIDATION_REJECT_COMMENT_REQUIRED = 'VALIDATION_REJECT_COMMENT_REQUIRED',

  // ── Insurance ──────────────────────────────────────────────────────────────
  INSURANCE_MEMBER_NOT_FOUND = 'INSURANCE_MEMBER_NOT_FOUND',
  INSURANCE_NOT_FOUND = 'INSURANCE_NOT_FOUND',
  INSURANCE_CURRENT_USER_REQUIRED = 'INSURANCE_CURRENT_USER_REQUIRED',
  INSURANCE_TYPE_REQUIRED = 'INSURANCE_TYPE_REQUIRED',
  INSURANCE_TYPE_INVALID = 'INSURANCE_TYPE_INVALID',
  INSURANCE_COVERAGE_AMOUNT_INVALID = 'INSURANCE_COVERAGE_AMOUNT_INVALID',
  INSURANCE_DATE_REQUIRED = 'INSURANCE_DATE_REQUIRED',
  INSURANCE_DATE_INVALID = 'INSURANCE_DATE_INVALID',

  // ── Clubs ──────────────────────────────────────────────────────────────────
  CLUB_NOT_FOUND = 'CLUB_NOT_FOUND',
  CLUB_SECTION_NOT_FOUND = 'CLUB_SECTION_NOT_FOUND',
  CLUB_TYPE_NOT_FOUND = 'CLUB_TYPE_NOT_FOUND',
  CLUB_SECTION_ID_REQUIRED = 'CLUB_SECTION_ID_REQUIRED',
  CLUB_ROLE_SLOT_LIMIT_REACHED = 'CLUB_ROLE_SLOT_LIMIT_REACHED',
  CLUB_ROLE_EXCLUSIVE_CONFLICT = 'CLUB_ROLE_EXCLUSIVE_CONFLICT',
  CLUB_NO_ACTIVE_YEAR = 'CLUB_NO_ACTIVE_YEAR',
  CLUB_ROLE_IDENTIFIER_REQUIRED = 'CLUB_ROLE_IDENTIFIER_REQUIRED',
  CLUB_ROLE_NOT_FOUND = 'CLUB_ROLE_NOT_FOUND',

  // ── Post-Registration ──────────────────────────────────────────────────────
  POST_REG_NOT_INITIATED = 'POST_REG_NOT_INITIATED',
  POST_REG_PHOTO_REQUIRED = 'POST_REG_PHOTO_REQUIRED',
  POST_REG_USER_NOT_FOUND = 'POST_REG_USER_NOT_FOUND',
  POST_REG_PERSONAL_INFO_INCOMPLETE = 'POST_REG_PERSONAL_INFO_INCOMPLETE',
  POST_REG_EMERGENCY_CONTACT_REQUIRED = 'POST_REG_EMERGENCY_CONTACT_REQUIRED',
  POST_REG_LEGAL_REP_REQUIRED = 'POST_REG_LEGAL_REP_REQUIRED',
  POST_REG_CLUB_NOT_FOUND = 'POST_REG_CLUB_NOT_FOUND',
  POST_REG_CLASS_NOT_FOUND = 'POST_REG_CLASS_NOT_FOUND',
  POST_REG_CLASS_NOT_ELIGIBLE = 'POST_REG_CLASS_NOT_ELIGIBLE',
  POST_REG_DUPLICATE_MEMBERSHIP = 'POST_REG_DUPLICATE_MEMBERSHIP',
  POST_REG_NO_ACTIVE_YEAR = 'POST_REG_NO_ACTIVE_YEAR',
  POST_REG_MEMBER_ROLE_NOT_FOUND = 'POST_REG_MEMBER_ROLE_NOT_FOUND',
  POST_REG_ASSIGNMENT_FAILED = 'POST_REG_ASSIGNMENT_FAILED',
  POST_REG_ENROLLMENT_FAILED = 'POST_REG_ENROLLMENT_FAILED',

  // ── Legal Representatives ──────────────────────────────────────────────────
  LEGAL_REP_NOT_REQUIRED = 'LEGAL_REP_NOT_REQUIRED',
  LEGAL_REP_ALREADY_EXISTS = 'LEGAL_REP_ALREADY_EXISTS',
  LEGAL_REP_DATA_REQUIRED = 'LEGAL_REP_DATA_REQUIRED',
  LEGAL_REP_USER_NOT_FOUND = 'LEGAL_REP_USER_NOT_FOUND',
  LEGAL_REP_RELATIONSHIP_TYPE_NOT_FOUND = 'LEGAL_REP_RELATIONSHIP_TYPE_NOT_FOUND',
  LEGAL_REP_OWNER_NOT_FOUND = 'LEGAL_REP_OWNER_NOT_FOUND',
  LEGAL_REP_NOT_FOUND = 'LEGAL_REP_NOT_FOUND',

  // ── Certifications ─────────────────────────────────────────────────────────
  CERT_NOT_FOUND = 'CERT_NOT_FOUND',
  CERT_ALREADY_ENROLLED = 'CERT_ALREADY_ENROLLED',
  CERT_ELIGIBILITY_REQUIRED = 'CERT_ELIGIBILITY_REQUIRED',
  CERT_ENROLLMENT_NOT_FOUND = 'CERT_ENROLLMENT_NOT_FOUND',
  CERT_SECTION_INVALID = 'CERT_SECTION_INVALID',

  // ── Achievements ───────────────────────────────────────────────────────────
  ACHIEVEMENT_CATEGORY_NOT_FOUND = 'ACHIEVEMENT_CATEGORY_NOT_FOUND',
  ACHIEVEMENT_CATEGORY_HAS_ACTIVE = 'ACHIEVEMENT_CATEGORY_HAS_ACTIVE',
  ACHIEVEMENT_NOT_FOUND = 'ACHIEVEMENT_NOT_FOUND',
  ACHIEVEMENT_BADGE_INVALID_TYPE = 'ACHIEVEMENT_BADGE_INVALID_TYPE',
  ACHIEVEMENT_BADGE_TOO_LARGE = 'ACHIEVEMENT_BADGE_TOO_LARGE',
  ACHIEVEMENT_INACTIVE = 'ACHIEVEMENT_INACTIVE',
  ACHIEVEMENT_PREREQUISITE_NOT_FOUND = 'ACHIEVEMENT_PREREQUISITE_NOT_FOUND',
  ACHIEVEMENT_CIRCULAR_PREREQUISITE = 'ACHIEVEMENT_CIRCULAR_PREREQUISITE',

  // ── Inventory ──────────────────────────────────────────────────────────────
  INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND',
  INVENTORY_CATEGORY_NOT_FOUND = 'INVENTORY_CATEGORY_NOT_FOUND',
  INVENTORY_SECTION_NOT_FOUND = 'INVENTORY_SECTION_NOT_FOUND',
  INVENTORY_EVIDENCE_FILE_REQUIRED = 'INVENTORY_EVIDENCE_FILE_REQUIRED',
  INVENTORY_EVIDENCE_LIMIT_EXCEEDED = 'INVENTORY_EVIDENCE_LIMIT_EXCEEDED',
  FINANCE_EVIDENCE_FILE_REQUIRED = 'FINANCE_EVIDENCE_FILE_REQUIRED',
  FINANCE_EVIDENCE_LIMIT_EXCEEDED = 'FINANCE_EVIDENCE_LIMIT_EXCEEDED',

  // ── Emergency Contacts ─────────────────────────────────────────────────────
  EC_INVALID_RELATIONSHIP_TYPE = 'EC_INVALID_RELATIONSHIP_TYPE',
  EC_MAX_CONTACTS_REACHED = 'EC_MAX_CONTACTS_REACHED',
  EC_ALREADY_EXISTS = 'EC_ALREADY_EXISTS',
  EC_NOT_FOUND = 'EC_NOT_FOUND',

  // ── Club Enrollments ───────────────────────────────────────────────────────
  CE_SECTION_NOT_FOUND = 'CE_SECTION_NOT_FOUND',
  CE_CLASS_NOT_FOUND = 'CE_CLASS_NOT_FOUND',
  CE_ALREADY_ENROLLED = 'CE_ALREADY_ENROLLED',
  CE_ENROLLMENT_NOT_FOUND = 'CE_ENROLLMENT_NOT_FOUND',
  CE_ECCLESIASTICAL_YEAR_REQUIRED = 'CE_ECCLESIASTICAL_YEAR_REQUIRED',
  CE_NO_ACTIVE_YEAR = 'CE_NO_ACTIVE_YEAR',

  // ── FCM Tokens ─────────────────────────────────────────────────────────────
  FCM_TOKEN_NOT_FOUND = 'FCM_TOKEN_NOT_FOUND',
  FCM_TOKEN_FORBIDDEN = 'FCM_TOKEN_FORBIDDEN',

  // ── Membership Requests ────────────────────────────────────────────────────
  MR_NOT_FOUND = 'MR_NOT_FOUND',
  MR_ALREADY_PENDING = 'MR_ALREADY_PENDING',

  // ── Finances ───────────────────────────────────────────────────────────────
  FINANCE_CLUB_NOT_FOUND = 'FINANCE_CLUB_NOT_FOUND',
  FINANCE_TRANSACTION_NOT_FOUND = 'FINANCE_TRANSACTION_NOT_FOUND',
  FINANCE_PERIOD_CLOSED = 'FINANCE_PERIOD_CLOSED',

  // ── Analytics ──────────────────────────────────────────────────────────────
  ANALYTICS_QUEUE_NOT_FOUND = 'ANALYTICS_QUEUE_NOT_FOUND',
  ANALYTICS_JOB_NOT_FOUND = 'ANALYTICS_JOB_NOT_FOUND',
  ANALYTICS_JOB_ACTIVE = 'ANALYTICS_JOB_ACTIVE',
  ANALYTICS_JOB_RETRY_FAILED = 'ANALYTICS_JOB_RETRY_FAILED',

  // ── Member of Month ────────────────────────────────────────────────────────
  MOM_FORBIDDEN = 'MOM_FORBIDDEN',
  MOM_SECTION_NOT_FOUND = 'MOM_SECTION_NOT_FOUND',
  MOM_PERIOD_NOT_FOUND = 'MOM_PERIOD_NOT_FOUND',

  // ── Monthly Reports PDF ────────────────────────────────────────────────────
  REPORT_PDF_NOT_FOUND = 'REPORT_PDF_NOT_FOUND',
  REPORT_PDF_NOT_GENERATED = 'REPORT_PDF_NOT_GENERATED',
  REPORT_PDF_NO_SNAPSHOT = 'REPORT_PDF_NO_SNAPSHOT',

  // ── Year End ───────────────────────────────────────────────────────────────
  YEAR_END_YEAR_CLOSED = 'YEAR_END_YEAR_CLOSED',
  YEAR_END_ECCLESIASTICAL_YEAR_NOT_FOUND = 'YEAR_END_ECCLESIASTICAL_YEAR_NOT_FOUND',

  // ── System Config ──────────────────────────────────────────────────────────
  SYSTEM_CONFIG_NOT_FOUND = 'SYSTEM_CONFIG_NOT_FOUND',

  // ── Cron Alerts ────────────────────────────────────────────────────────────
  CRON_ALERT_NOT_FOUND = 'CRON_ALERT_NOT_FOUND',

  // ── Notifications ──────────────────────────────────────────────────────────
  NOTIF_SEND_FORBIDDEN = 'NOTIF_SEND_FORBIDDEN',
  NOTIF_NOT_FOUND = 'NOTIF_NOT_FOUND',
  NOTIF_TARGET_TYPE_MISMATCH = 'NOTIF_TARGET_TYPE_MISMATCH',

  // ── Data Export ────────────────────────────────────────────────────────────
  EXPORT_NOT_FOUND = 'EXPORT_NOT_FOUND',
  EXPORT_ALREADY_PROCESSING = 'EXPORT_ALREADY_PROCESSING',

  // ── MFA ────────────────────────────────────────────────────────────────────
  MFA_CODE_INVALID = 'MFA_CODE_INVALID',

  // ── Auth (additional) ─────────────────────────────────────────────────────
  AUTH_EMAIL_ALREADY_IN_USE = 'AUTH_EMAIL_ALREADY_IN_USE',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_TOTP_NOT_ENROLLED = 'AUTH_TOTP_NOT_ENROLLED',
  AUTH_TOTP_ENROLLMENT_FAILED = 'AUTH_TOTP_ENROLLMENT_FAILED',
  AUTH_OAUTH_CALLBACK_FAILED = 'AUTH_OAUTH_CALLBACK_FAILED',

  // ── Guards ─────────────────────────────────────────────────────────────────
  GUARD_USER_NOT_AUTHENTICATED = 'GUARD_USER_NOT_AUTHENTICATED',
  GUARD_RBAC_MISCONFIGURATION = 'GUARD_RBAC_MISCONFIGURATION',
  GUARD_PERMISSION_DENIED = 'GUARD_PERMISSION_DENIED',
  GUARD_CLUB_SCOPE_REQUIRED = 'GUARD_CLUB_SCOPE_REQUIRED',
  GUARD_CLUB_ID_REQUIRED = 'GUARD_CLUB_ID_REQUIRED',
  GUARD_MFA_REQUIRED = 'GUARD_MFA_REQUIRED',
  GUARD_JWT_UNAUTHORIZED = 'GUARD_JWT_UNAUTHORIZED',
  GUARD_OWNER_OR_ADMIN_REQUIRED = 'GUARD_OWNER_OR_ADMIN_REQUIRED',
  GUARD_USER_ID_PARAM_MISSING = 'GUARD_USER_ID_PARAM_MISSING',
  GUARD_ASSIGNMENT_SCOPE_INVALID = 'GUARD_ASSIGNMENT_SCOPE_INVALID',
  GUARD_ASSIGNMENT_NOT_FOUND = 'GUARD_ASSIGNMENT_NOT_FOUND',

  // ── File Validation ───────────────────────────────────────────────────────
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_INVALID = 'FILE_TYPE_INVALID',
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_FIELD_UNEXPECTED = 'FILE_FIELD_UNEXPECTED',

  // ── R2 Storage ────────────────────────────────────────────────────────────
  R2_UPLOAD_FAILED = 'R2_UPLOAD_FAILED',
  R2_DELETE_FAILED = 'R2_DELETE_FAILED',
  R2_SIGNED_URL_FAILED = 'R2_SIGNED_URL_FAILED',
  R2_VALIDATION_FAILED = 'R2_VALIDATION_FAILED',

  // ── Authorization Context ─────────────────────────────────────────────────
  AUTH_CONTEXT_USER_NOT_FOUND = 'AUTH_CONTEXT_USER_NOT_FOUND',

  // ── RBAC Controller ───────────────────────────────────────────────────────
  RBAC_BOOTSTRAP_FORBIDDEN = 'RBAC_BOOTSTRAP_FORBIDDEN',
  RBAC_BOOTSTRAP_SECRET_INVALID = 'RBAC_BOOTSTRAP_SECRET_INVALID',

  // ── Notifications Controller ──────────────────────────────────────────────
  NOTIF_BROADCAST_USER_ID_FORBIDDEN = 'NOTIF_BROADCAST_USER_ID_FORBIDDEN',
  NOTIF_INVALID_CATEGORY = 'NOTIF_INVALID_CATEGORY',

  // ── System Config Controller ──────────────────────────────────────────────
  SYSTEM_CONFIG_VALUE_REQUIRED = 'SYSTEM_CONFIG_VALUE_REQUIRED',

  // ── Achievements Controller ───────────────────────────────────────────────
  ACHIEVEMENT_BADGE_UPLOAD_MISSING = 'ACHIEVEMENT_BADGE_UPLOAD_MISSING',

  // ── QR ────────────────────────────────────────────────────────────────────
  QR_MEMBER_NOT_FOUND = 'QR_MEMBER_NOT_FOUND',
  QR_TOKEN_INVALID = 'QR_TOKEN_INVALID',
  QR_ACTIVITY_NOT_FOUND = 'QR_ACTIVITY_NOT_FOUND',
  QR_ACTIVITY_SCOPE_INVALID = 'QR_ACTIVITY_SCOPE_INVALID',
  QR_ACCESS_DENIED = 'QR_ACCESS_DENIED',

  // ── Translations (i18n write) ─────────────────────────────────────────────
  TRANSLATIONS_ES_NOT_ALLOWED = 'TRANSLATIONS_ES_NOT_ALLOWED',
  TRANSLATIONS_INVALID_LOCALE = 'TRANSLATIONS_INVALID_LOCALE',
  TRANSLATIONS_DUPLICATE_LOCALE = 'TRANSLATIONS_DUPLICATE_LOCALE',

  // ── Rankings ──────────────────────────────────────────────────────────────
  RANKING_WEIGHTS_DEFAULT_NOT_FOUND = 'RANKING_WEIGHTS_DEFAULT_NOT_FOUND',

  // ── Member Rankings ───────────────────────────────────────────────────────
  MEMBER_RANKING_NOT_FOUND = 'MEMBER_RANKING_NOT_FOUND',
  MEMBER_RANKING_HIDDEN = 'MEMBER_RANKING_HIDDEN',
  MEMBER_RANKING_SCOPE_DENIED = 'MEMBER_RANKING_SCOPE_DENIED',
  RECALCULATION_DISABLED = 'RECALCULATION_DISABLED',

  // ── Member Ranking Weights ────────────────────────────────────────────────
  WEIGHTS_SUM_INVALID = 'WEIGHTS_SUM_INVALID',
  WEIGHTS_CONFLICT = 'WEIGHTS_CONFLICT',
  DEFAULT_WEIGHTS_NOT_DELETABLE = 'DEFAULT_WEIGHTS_NOT_DELETABLE',
  WEIGHTS_NOT_FOUND = 'WEIGHTS_NOT_FOUND',

  // ── Ranking Weights (domain errors) ──────────────────────────────────────
  RANKING_WEIGHTS_DEFAULT_NOT_DELETABLE = 'RANKING_WEIGHTS_DEFAULT_NOT_DELETABLE',
  RANKING_WEIGHTS_NOT_FOUND = 'RANKING_WEIGHTS_NOT_FOUND',
  RANKING_WEIGHTS_GLOBAL_RESERVED = 'RANKING_WEIGHTS_GLOBAL_RESERVED',
  RANKING_WEIGHTS_SUM_INVALID = 'RANKING_WEIGHTS_SUM_INVALID',
  RANKING_WEIGHTS_CLUB_TYPE_CONFLICT = 'RANKING_WEIGHTS_CLUB_TYPE_CONFLICT',
  ANNUAL_RANKING_CONFIG_NOT_FOUND = 'ANNUAL_RANKING_CONFIG_NOT_FOUND',
  ANNUAL_RANKING_CONFIG_CONFLICT = 'ANNUAL_RANKING_CONFIG_CONFLICT',
  ANNUAL_RANKING_COMPONENT_SUM_INVALID = 'ANNUAL_RANKING_COMPONENT_SUM_INVALID',
  ANNUAL_RANKING_AXIS_SUM_INVALID = 'ANNUAL_RANKING_AXIS_SUM_INVALID',
  ANNUAL_RANKING_AXIS_COMPONENT_SUM_INVALID = 'ANNUAL_RANKING_AXIS_COMPONENT_SUM_INVALID',
  ANNUAL_RANKING_COMPONENT_UNKNOWN = 'ANNUAL_RANKING_COMPONENT_UNKNOWN',
  ANNUAL_RANKING_COMPONENT_DUPLICATE = 'ANNUAL_RANKING_COMPONENT_DUPLICATE',
  ANNUAL_RANKING_SCOPE_INVALID = 'ANNUAL_RANKING_SCOPE_INVALID',
  ANNUAL_RANKING_UNION_SCOPE_CONFLICT = 'ANNUAL_RANKING_UNION_SCOPE_CONFLICT',
  ANNUAL_RANKING_ANNUAL_FOLDER_COMPONENT_REQUIRED = 'ANNUAL_RANKING_ANNUAL_FOLDER_COMPONENT_REQUIRED',
  ANNUAL_RANKING_CONFIG_HAS_FOLDERS = 'ANNUAL_RANKING_CONFIG_HAS_FOLDERS',
  ANNUAL_RANKING_SECTION_NOT_FOUND = 'ANNUAL_RANKING_SECTION_NOT_FOUND',
  ANNUAL_RANKING_SECTION_NO_CLUB = 'ANNUAL_RANKING_SECTION_NO_CLUB',

  // ── Member Rankings (domain errors) ──────────────────────────────────────
  MEMBER_RANKINGS_CLUB_ID_INVALID = 'MEMBER_RANKINGS_CLUB_ID_INVALID',

  // ── Camporee Events ───────────────────────────────────────────────────────
  ADMIN_CAMPOREE_EVENT_TYPE_NOT_FOUND = 'ADMIN_CAMPOREE_EVENT_TYPE_NOT_FOUND',
  ADMIN_CAMPOREE_EVENT_TYPE_CODE_CONFLICT = 'ADMIN_CAMPOREE_EVENT_TYPE_CODE_CONFLICT',
  ADMIN_CAMPOREE_EVENT_TYPE_NAME_CONFLICT = 'ADMIN_CAMPOREE_EVENT_TYPE_NAME_CONFLICT',
  CAMPOREE_EVENT_TEMPLATE_NOT_FOUND = 'CAMPOREE_EVENT_TEMPLATE_NOT_FOUND',
  CAMPOREE_EVENT_TEMPLATE_SCOPE_INVALID = 'CAMPOREE_EVENT_TEMPLATE_SCOPE_INVALID',
  CAMPOREE_EVENT_TEMPLATE_ACCESS_DENIED = 'CAMPOREE_EVENT_TEMPLATE_ACCESS_DENIED',
  CAMPOREE_EVENT_TEMPLATE_POINTS_INVALID = 'CAMPOREE_EVENT_TEMPLATE_POINTS_INVALID',
  CAMPOREE_EVENT_TEMPLATE_PARTICIPANTS_INVALID = 'CAMPOREE_EVENT_TEMPLATE_PARTICIPANTS_INVALID',
  CAMPOREE_EVENT_NOT_FOUND = 'CAMPOREE_EVENT_NOT_FOUND',
  CAMPOREE_EVENT_ACCESS_DENIED = 'CAMPOREE_EVENT_ACCESS_DENIED',
  CAMPOREE_EVENT_CAMPOREE_NOT_FOUND = 'CAMPOREE_EVENT_CAMPOREE_NOT_FOUND',
  CAMPOREE_EVENT_SECTIONS_INVALID = 'CAMPOREE_EVENT_SECTIONS_INVALID',
  CAMPOREE_EVENT_STATUS_TRANSITION_INVALID = 'CAMPOREE_EVENT_STATUS_TRANSITION_INVALID',
  CAMPOREE_EVENT_LEADER_CONFLICT = 'CAMPOREE_EVENT_LEADER_CONFLICT',
  CAMPOREE_EVENT_VENUE_SCOPE_MISMATCH = 'CAMPOREE_EVENT_VENUE_SCOPE_MISMATCH',

  // ── Camporee Venues ───────────────────────────────────────────────────────
  CAMPOREE_VENUE_NOT_FOUND = 'CAMPOREE_VENUE_NOT_FOUND',
  CAMPOREE_VENUE_SCOPE_INVALID = 'CAMPOREE_VENUE_SCOPE_INVALID',
}
