/**
 * Canonical error codes for the SACDIA API.
 *
 * Rules:
 *   - ALL_CAPS_SNAKE format
 *   - Domain-namespaced (AUTH_, CLUB_, RBAC_, etc.)
 *   - Each code MUST have a corresponding entry in all src/i18n/{locale}/errors.json files
 *   - Phase A: generic + auth sample keys. Phase B: migrate all modules here.
 */
export enum ErrorCode {
  // ── Generic ────────────────────────────────────────────────────────────────
  GENERIC_ERROR = 'GENERIC_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // ── Database / Prisma ──────────────────────────────────────────────────────
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  RECORD_CONFLICT = 'RECORD_CONFLICT',
  RECORD_FK_VIOLATION = 'RECORD_FK_VIOLATION',
  RECORD_RELATED_NOT_FOUND = 'RECORD_RELATED_NOT_FOUND',

  // ── Auth (sample — full migration in Phase B) ──────────────────────────────
  AUTH_REFRESH_TOKEN_REQUIRED = 'AUTH_REFRESH_TOKEN_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',

  // ── Annual Folders ─────────────────────────────────────────────────────────
  ANNUAL_FOLDER_OWNER_REQUIRED = 'ANNUAL_FOLDER_OWNER_REQUIRED',
  ANNUAL_FOLDER_CLUB_TYPE_NOT_FOUND = 'ANNUAL_FOLDER_CLUB_TYPE_NOT_FOUND',
  ANNUAL_FOLDER_YEAR_NOT_FOUND = 'ANNUAL_FOLDER_YEAR_NOT_FOUND',
  ANNUAL_FOLDER_TEMPLATE_NOT_FOUND = 'ANNUAL_FOLDER_TEMPLATE_NOT_FOUND',
  ANNUAL_FOLDER_TEMPLATE_SECTION_NOT_FOUND = 'ANNUAL_FOLDER_TEMPLATE_SECTION_NOT_FOUND',
  ANNUAL_FOLDER_SECTION_HAS_EVIDENCES = 'ANNUAL_FOLDER_SECTION_HAS_EVIDENCES',
  ANNUAL_FOLDER_TEMPLATE_NO_MATCH = 'ANNUAL_FOLDER_TEMPLATE_NO_MATCH',
  ANNUAL_FOLDER_ALREADY_EXISTS = 'ANNUAL_FOLDER_ALREADY_EXISTS',
  ANNUAL_FOLDER_NOT_FOUND = 'ANNUAL_FOLDER_NOT_FOUND',
  ANNUAL_FOLDER_ENROLLMENT_NOT_FOUND = 'ANNUAL_FOLDER_ENROLLMENT_NOT_FOUND',
  ANNUAL_FOLDER_FILE_REQUIRED = 'ANNUAL_FOLDER_FILE_REQUIRED',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_UPLOAD = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_UPLOAD',
  ANNUAL_FOLDER_SECTION_NOT_IN_TEMPLATE = 'ANNUAL_FOLDER_SECTION_NOT_IN_TEMPLATE',
  ANNUAL_FOLDER_EVIDENCE_CLUB_NOT_RESOLVED = 'ANNUAL_FOLDER_EVIDENCE_CLUB_NOT_RESOLVED',
  ANNUAL_FOLDER_EVIDENCE_ACCESS_DENIED = 'ANNUAL_FOLDER_EVIDENCE_ACCESS_DENIED',
  ANNUAL_FOLDER_FOLDER_ACCESS_DENIED = 'ANNUAL_FOLDER_FOLDER_ACCESS_DENIED',
  ANNUAL_FOLDER_EVIDENCE_TERRITORY_DENIED = 'ANNUAL_FOLDER_EVIDENCE_TERRITORY_DENIED',
  ANNUAL_FOLDER_EVIDENCE_NOT_FOUND = 'ANNUAL_FOLDER_EVIDENCE_NOT_FOUND',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_MUTATION = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_MUTATION',
  ANNUAL_FOLDER_SECTION_NO_EVIDENCE = 'ANNUAL_FOLDER_SECTION_NO_EVIDENCE',
  ANNUAL_FOLDER_STATUS_CONFLICT = 'ANNUAL_FOLDER_STATUS_CONFLICT',
  ANNUAL_FOLDER_CLUB_NO_PARENT = 'ANNUAL_FOLDER_CLUB_NO_PARENT',
  ANNUAL_FOLDER_CLUB_NO_LOCAL_FIELD = 'ANNUAL_FOLDER_CLUB_NO_LOCAL_FIELD',
  ANNUAL_FOLDER_CAMPOREE_CLUB_TYPE_INVALID = 'ANNUAL_FOLDER_CAMPOREE_CLUB_TYPE_INVALID',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_EVALUATE = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_EVALUATE',
  ANNUAL_FOLDER_EVAL_ROW_NOT_FOUND = 'ANNUAL_FOLDER_EVAL_ROW_NOT_FOUND',
  ANNUAL_FOLDER_SECTION_PENDING = 'ANNUAL_FOLDER_SECTION_PENDING',
  ANNUAL_FOLDER_SECTION_TERMINAL = 'ANNUAL_FOLDER_SECTION_TERMINAL',
  ANNUAL_FOLDER_EARNED_POINTS_EXCEED_MAX = 'ANNUAL_FOLDER_EARNED_POINTS_EXCEED_MAX',
  ANNUAL_FOLDER_UNION_ROLE_REQUIRED = 'ANNUAL_FOLDER_UNION_ROLE_REQUIRED',
  ANNUAL_FOLDER_UNION_CONFIRMATION_NOT_REQUIRED = 'ANNUAL_FOLDER_UNION_CONFIRMATION_NOT_REQUIRED',
  ANNUAL_FOLDER_SECTION_NOT_PREAPPROVED = 'ANNUAL_FOLDER_SECTION_NOT_PREAPPROVED',
  ANNUAL_FOLDER_SECTION_MISSING_LF_DATA = 'ANNUAL_FOLDER_SECTION_MISSING_LF_DATA',
  ANNUAL_FOLDER_STATUS_INVALID_FOR_REOPEN = 'ANNUAL_FOLDER_STATUS_INVALID_FOR_REOPEN',
  ANNUAL_FOLDER_SECTION_NOT_REOPENABLE = 'ANNUAL_FOLDER_SECTION_NOT_REOPENABLE',
  ANNUAL_FOLDER_RANKINGS_LOCK_CONFLICT = 'ANNUAL_FOLDER_RANKINGS_LOCK_CONFLICT',
  ANNUAL_FOLDER_ENROLLMENT_FOR_RANKING_NOT_FOUND = 'ANNUAL_FOLDER_ENROLLMENT_FOR_RANKING_NOT_FOUND',

  // ── Award Categories ───────────────────────────────────────────────────────
  AWARD_CATEGORY_POINTS_INVALID = 'AWARD_CATEGORY_POINTS_INVALID',
  AWARD_CATEGORY_CLUB_TYPE_NOT_FOUND = 'AWARD_CATEGORY_CLUB_TYPE_NOT_FOUND',
  AWARD_CATEGORY_NOT_FOUND = 'AWARD_CATEGORY_NOT_FOUND',

  // ── Camporees ──────────────────────────────────────────────────────────────
  CAMPOREE_NOT_FOUND = 'CAMPOREE_NOT_FOUND',
  CAMPOREE_NOT_ACTIVE = 'CAMPOREE_NOT_ACTIVE',
  CAMPOREE_YEAR_NOT_ACTIVE = 'CAMPOREE_YEAR_NOT_ACTIVE',
  CAMPOREE_LOCAL_FIELD_NOT_FOUND = 'CAMPOREE_LOCAL_FIELD_NOT_FOUND',
  CAMPOREE_UNION_NOT_FOUND = 'CAMPOREE_UNION_NOT_FOUND',
  CAMPOREE_LOCAL_FIELD_INVALID = 'CAMPOREE_LOCAL_FIELD_INVALID',
  CAMPOREE_MEMBER_NOT_FOUND = 'CAMPOREE_MEMBER_NOT_FOUND',
  CAMPOREE_MEMBER_ALREADY_REGISTERED = 'CAMPOREE_MEMBER_ALREADY_REGISTERED',
  CAMPOREE_USER_NOT_FOUND = 'CAMPOREE_USER_NOT_FOUND',
  CAMPOREE_INSURANCE_NOT_FOUND = 'CAMPOREE_INSURANCE_NOT_FOUND',
  CAMPOREE_INSURANCE_NOT_OWNER = 'CAMPOREE_INSURANCE_NOT_OWNER',
  CAMPOREE_INSURANCE_TYPE_INVALID = 'CAMPOREE_INSURANCE_TYPE_INVALID',
  CAMPOREE_INSURANCE_EXPIRED = 'CAMPOREE_INSURANCE_EXPIRED',
  CAMPOREE_INSURANCE_NOT_ACTIVE = 'CAMPOREE_INSURANCE_NOT_ACTIVE',
  CAMPOREE_CLUB_SECTION_NOT_FOUND = 'CAMPOREE_CLUB_SECTION_NOT_FOUND',
  CAMPOREE_CLUB_ALREADY_ENROLLED = 'CAMPOREE_CLUB_ALREADY_ENROLLED',
  CAMPOREE_CLUB_ENROLLMENT_NOT_FOUND = 'CAMPOREE_CLUB_ENROLLMENT_NOT_FOUND',
  CAMPOREE_CLUB_LOCAL_FIELD_UNKNOWN = 'CAMPOREE_CLUB_LOCAL_FIELD_UNKNOWN',
  CAMPOREE_CLUB_LOCAL_FIELD_NOT_PARTICIPATING = 'CAMPOREE_CLUB_LOCAL_FIELD_NOT_PARTICIPATING',
  CAMPOREE_PAYMENT_NOT_FOUND = 'CAMPOREE_PAYMENT_NOT_FOUND',
  CAMPOREE_UNION_CAMPOREE_NOT_FOUND = 'CAMPOREE_UNION_CAMPOREE_NOT_FOUND',
  CAMPOREE_UNION_ACCESS_DENIED = 'CAMPOREE_UNION_ACCESS_DENIED',
  CAMPOREE_LOCAL_FIELD_ACCESS_DENIED = 'CAMPOREE_LOCAL_FIELD_ACCESS_DENIED',
  CAMPOREE_CLUB_ENROLLMENT_PENDING_NOT_FOUND = 'CAMPOREE_CLUB_ENROLLMENT_PENDING_NOT_FOUND',
  CAMPOREE_MEMBER_ENROLLMENT_PENDING_NOT_FOUND = 'CAMPOREE_MEMBER_ENROLLMENT_PENDING_NOT_FOUND',
  CAMPOREE_PAYMENT_PENDING_NOT_FOUND = 'CAMPOREE_PAYMENT_PENDING_NOT_FOUND',

  // ── Admin — Users ──────────────────────────────────────────────────────────
  ADMIN_USER_NOT_FOUND = 'ADMIN_USER_NOT_FOUND',
  ADMIN_USER_SCOPE_MISSING = 'ADMIN_USER_SCOPE_MISSING',
  ADMIN_USER_NO_GLOBAL_PERMISSIONS = 'ADMIN_USER_NO_GLOBAL_PERMISSIONS',
  ADMIN_USER_MFA_NOT_ENABLED = 'ADMIN_USER_MFA_NOT_ENABLED',

  // ── Admin — Auth / Sessions ────────────────────────────────────────────────
  ADMIN_SESSION_NOT_FOUND = 'ADMIN_SESSION_NOT_FOUND',

  // ── Admin — Honors / Requirements ─────────────────────────────────────────
  ADMIN_HONOR_NOT_FOUND = 'ADMIN_HONOR_NOT_FOUND',
  ADMIN_HONOR_REQUIREMENT_NOT_FOUND = 'ADMIN_HONOR_REQUIREMENT_NOT_FOUND',
  ADMIN_HONOR_REQUIREMENT_WRONG_HONOR = 'ADMIN_HONOR_REQUIREMENT_WRONG_HONOR',
  ADMIN_HONOR_REQUIREMENT_CHOICE_MIN_REQUIRED = 'ADMIN_HONOR_REQUIREMENT_CHOICE_MIN_REQUIRED',

  // ── Admin — Geography ──────────────────────────────────────────────────────
  ADMIN_COUNTRY_NOT_FOUND = 'ADMIN_COUNTRY_NOT_FOUND',
  ADMIN_COUNTRY_NAME_CONFLICT = 'ADMIN_COUNTRY_NAME_CONFLICT',
  ADMIN_COUNTRY_ABBREVIATION_CONFLICT = 'ADMIN_COUNTRY_ABBREVIATION_CONFLICT',
  ADMIN_COUNTRY_HAS_ACTIVE_UNIONS = 'ADMIN_COUNTRY_HAS_ACTIVE_UNIONS',
  ADMIN_UNION_NOT_FOUND = 'ADMIN_UNION_NOT_FOUND',
  ADMIN_UNION_NAME_CONFLICT = 'ADMIN_UNION_NAME_CONFLICT',
  ADMIN_UNION_ABBREVIATION_CONFLICT = 'ADMIN_UNION_ABBREVIATION_CONFLICT',
  ADMIN_UNION_HAS_ACTIVE_LOCAL_FIELDS = 'ADMIN_UNION_HAS_ACTIVE_LOCAL_FIELDS',
  ADMIN_LOCAL_FIELD_NOT_FOUND = 'ADMIN_LOCAL_FIELD_NOT_FOUND',
  ADMIN_LOCAL_FIELD_NAME_CONFLICT = 'ADMIN_LOCAL_FIELD_NAME_CONFLICT',
  ADMIN_LOCAL_FIELD_ABBREVIATION_CONFLICT = 'ADMIN_LOCAL_FIELD_ABBREVIATION_CONFLICT',
  ADMIN_LOCAL_FIELD_HAS_ACTIVE_DISTRICTS = 'ADMIN_LOCAL_FIELD_HAS_ACTIVE_DISTRICTS',
  ADMIN_DISTRICT_NOT_FOUND = 'ADMIN_DISTRICT_NOT_FOUND',
  ADMIN_DISTRICT_NAME_CONFLICT = 'ADMIN_DISTRICT_NAME_CONFLICT',
  ADMIN_DISTRICT_HAS_ACTIVE_CHURCHES = 'ADMIN_DISTRICT_HAS_ACTIVE_CHURCHES',
  ADMIN_CHURCH_NOT_FOUND = 'ADMIN_CHURCH_NOT_FOUND',
  ADMIN_CHURCH_NAME_CONFLICT = 'ADMIN_CHURCH_NAME_CONFLICT',

  // ── Admin — Reference Catalogs ─────────────────────────────────────────────
  ADMIN_ACTIVITY_TYPE_NOT_FOUND = 'ADMIN_ACTIVITY_TYPE_NOT_FOUND',
  ADMIN_ACTIVITY_TYPE_NAME_CONFLICT = 'ADMIN_ACTIVITY_TYPE_NAME_CONFLICT',
  ADMIN_ACTIVITY_TYPE_CODE_CONFLICT = 'ADMIN_ACTIVITY_TYPE_CODE_CONFLICT',
  ADMIN_ACTIVITY_TYPE_IN_USE = 'ADMIN_ACTIVITY_TYPE_IN_USE',
  ADMIN_RELATIONSHIP_TYPE_NOT_FOUND = 'ADMIN_RELATIONSHIP_TYPE_NOT_FOUND',
  ADMIN_RELATIONSHIP_TYPE_NAME_CONFLICT = 'ADMIN_RELATIONSHIP_TYPE_NAME_CONFLICT',
  ADMIN_RELATIONSHIP_TYPE_IN_USE = 'ADMIN_RELATIONSHIP_TYPE_IN_USE',
  ADMIN_ALLERGY_NOT_FOUND = 'ADMIN_ALLERGY_NOT_FOUND',
  ADMIN_ALLERGY_NAME_CONFLICT = 'ADMIN_ALLERGY_NAME_CONFLICT',
  ADMIN_ALLERGY_IN_USE = 'ADMIN_ALLERGY_IN_USE',
  ADMIN_DISEASE_NOT_FOUND = 'ADMIN_DISEASE_NOT_FOUND',
  ADMIN_DISEASE_NAME_CONFLICT = 'ADMIN_DISEASE_NAME_CONFLICT',
  ADMIN_DISEASE_IN_USE = 'ADMIN_DISEASE_IN_USE',
  ADMIN_MEDICINE_NOT_FOUND = 'ADMIN_MEDICINE_NOT_FOUND',
  ADMIN_MEDICINE_NAME_CONFLICT = 'ADMIN_MEDICINE_NAME_CONFLICT',
  ADMIN_MEDICINE_IN_USE = 'ADMIN_MEDICINE_IN_USE',
  ADMIN_ECCLESIASTICAL_YEAR_NOT_FOUND = 'ADMIN_ECCLESIASTICAL_YEAR_NOT_FOUND',
  ADMIN_ECCLESIASTICAL_YEAR_DATE_INVALID = 'ADMIN_ECCLESIASTICAL_YEAR_DATE_INVALID',
  ADMIN_ECCLESIASTICAL_YEAR_HAS_ACTIVE_ASSIGNMENTS = 'ADMIN_ECCLESIASTICAL_YEAR_HAS_ACTIVE_ASSIGNMENTS',
  ADMIN_CLUB_TYPE_NOT_FOUND = 'ADMIN_CLUB_TYPE_NOT_FOUND',
  ADMIN_CLUB_TYPE_NAME_CONFLICT = 'ADMIN_CLUB_TYPE_NAME_CONFLICT',
  ADMIN_CLUB_TYPE_IN_USE = 'ADMIN_CLUB_TYPE_IN_USE',
  ADMIN_CLUB_IDEAL_NOT_FOUND = 'ADMIN_CLUB_IDEAL_NOT_FOUND',
  ADMIN_HONOR_CATEGORY_NOT_FOUND = 'ADMIN_HONOR_CATEGORY_NOT_FOUND',
  ADMIN_HONOR_CATEGORY_NAME_CONFLICT = 'ADMIN_HONOR_CATEGORY_NAME_CONFLICT',
  ADMIN_HONOR_CATEGORY_IN_USE = 'ADMIN_HONOR_CATEGORY_IN_USE',
}
