-- Series headers for bulk-created independent activities.
-- Spec: docs/superpowers/specs/2026-09-02-actividades-recurrentes-design.md

CREATE TABLE IF NOT EXISTS "activity_series" (
    "activity_series_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "club_id" INTEGER NOT NULL,
    "ecclesiastical_year_id" INTEGER NOT NULL,
    "created_by" UUID NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "description" TEXT,
    "club_type_id" INTEGER NOT NULL,
    "club_section_id" INTEGER,
    "is_joint" BOOLEAN NOT NULL DEFAULT false,
    "lat" DOUBLE PRECISION NOT NULL,
    "long" DOUBLE PRECISION NOT NULL,
    "activity_time" VARCHAR(10) NOT NULL DEFAULT '09:00',
    "duration_days" INTEGER NOT NULL DEFAULT 0,
    "activity_place" TEXT NOT NULL,
    "image" TEXT NOT NULL DEFAULT '',
    "platform" INTEGER NOT NULL DEFAULT 0,
    "activity_type_id" INTEGER NOT NULL,
    "link_meet" TEXT,
    "additional_data" TEXT,
    "classes" JSONB,
    "first_date" DATE NOT NULL,
    "kind" VARCHAR(16) NOT NULL,
    "interval_days" INTEGER,
    "weekdays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
    "until_date" DATE NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "activity_series_pkey" PRIMARY KEY ("activity_series_id"),
    CONSTRAINT "activity_series_kind_check"
        CHECK ("kind" IN ('interval', 'weekly')),
    CONSTRAINT "activity_series_interval_check"
        CHECK (
            ("kind" = 'interval' AND "interval_days" IS NOT NULL AND "interval_days" >= 1)
            OR ("kind" = 'weekly' AND COALESCE(array_length("weekdays", 1), 0) >= 1)
        ),
    CONSTRAINT "activity_series_club_id_fkey"
        FOREIGN KEY ("club_id") REFERENCES "clubs"("club_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_year_id_fkey"
        FOREIGN KEY ("ecclesiastical_year_id") REFERENCES "ecclesiastical_years"("year_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_created_by_fkey"
        FOREIGN KEY ("created_by") REFERENCES "users"("user_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_club_type_id_fkey"
        FOREIGN KEY ("club_type_id") REFERENCES "club_types"("club_type_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_club_section_id_fkey"
        FOREIGN KEY ("club_section_id") REFERENCES "club_sections"("club_section_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_activity_type_id_fkey"
        FOREIGN KEY ("activity_type_id") REFERENCES "activity_types"("activity_type_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_activity_series_club"
    ON "activity_series"("club_id");
CREATE INDEX IF NOT EXISTS "idx_activity_series_year"
    ON "activity_series"("ecclesiastical_year_id");
CREATE INDEX IF NOT EXISTS "idx_activity_series_created_by"
    ON "activity_series"("created_by");

CREATE TABLE IF NOT EXISTS "activity_series_sections" (
    "activity_series_id" INTEGER NOT NULL,
    "club_section_id" INTEGER NOT NULL,

    CONSTRAINT "activity_series_sections_pkey"
        PRIMARY KEY ("activity_series_id", "club_section_id"),
    CONSTRAINT "activity_series_sections_series_fkey"
        FOREIGN KEY ("activity_series_id") REFERENCES "activity_series"("activity_series_id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "activity_series_sections_section_fkey"
        FOREIGN KEY ("club_section_id") REFERENCES "club_sections"("club_section_id")
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_activity_series_sections_section"
    ON "activity_series_sections"("club_section_id");

ALTER TABLE "activities"
    ADD COLUMN IF NOT EXISTS "activity_series_id" INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'activities_activity_series_id_fkey'
    ) THEN
        ALTER TABLE "activities"
            ADD CONSTRAINT "activities_activity_series_id_fkey"
            FOREIGN KEY ("activity_series_id") REFERENCES "activity_series"("activity_series_id")
            ON DELETE SET NULL ON UPDATE NO ACTION;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_activities_activity_series_id"
    ON "activities"("activity_series_id");

CREATE UNIQUE INDEX IF NOT EXISTS "activities_series_date_unique"
    ON "activities"("activity_series_id", "activity_date")
    WHERE "activity_series_id" IS NOT NULL;
