-- Master honor requirements schema (Task 1)

CREATE TYPE "master_honor_applicability_scope_enum" AS ENUM ('ALL', 'SELECTED_DIVISIONS');
CREATE TYPE "master_honor_requirement_group_type_enum" AS ENUM ('EXPLICIT_OPTIONS', 'CATEGORY_COUNT');
CREATE TYPE "user_master_honor_status_enum" AS ENUM ('AWARDED', 'REVOKED', 'RETIRED');
CREATE TYPE "user_master_honor_source_enum" AS ENUM ('AUTO');
CREATE TYPE "user_master_honor_status_reason_enum" AS ENUM (
  'CRITERIA_CHANGED',
  'USER_NO_LONGER_QUALIFIES',
  'MASTER_HONOR_INACTIVE',
  'RECOVERED'
);

ALTER TABLE "master_honors"
  ADD COLUMN "applicability_scope" "master_honor_applicability_scope_enum" NOT NULL DEFAULT 'ALL',
  ADD COLUMN "philosophy" TEXT,
  ADD COLUMN "notes" TEXT;

CREATE TABLE "master_honor_divisions" (
  "master_honor_division_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "master_honor_id" INTEGER NOT NULL,
  "division_id" INTEGER NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

  CONSTRAINT "master_honor_divisions_pkey" PRIMARY KEY ("master_honor_division_id"),
  CONSTRAINT "master_honor_divisions_master_honor_id_fkey" FOREIGN KEY ("master_honor_id")
    REFERENCES "master_honors" ("master_honor_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "master_honor_divisions_division_id_fkey" FOREIGN KEY ("division_id")
    REFERENCES "divisions" ("division_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "master_honor_divisions_master_honor_id_division_id_key"
    UNIQUE ("master_honor_id", "division_id")
);

CREATE INDEX "master_honor_divisions_division_id_idx" ON "master_honor_divisions" ("division_id");

CREATE TABLE "master_honor_requirement_groups" (
  "group_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "master_honor_id" INTEGER NOT NULL,
  "group_type" "master_honor_requirement_group_type_enum" NOT NULL,
  "title" VARCHAR(200),
  "description" TEXT,
  "minimum_required" INTEGER NOT NULL,
  "honors_category_id" INTEGER,
  "display_order" INTEGER NOT NULL DEFAULT 0,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

  CONSTRAINT "master_honor_requirement_groups_pkey" PRIMARY KEY ("group_id"),
  CONSTRAINT "master_honor_requirement_groups_master_honor_id_fkey" FOREIGN KEY ("master_honor_id")
    REFERENCES "master_honors" ("master_honor_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "master_honor_requirement_groups_honors_category_id_fkey" FOREIGN KEY ("honors_category_id")
    REFERENCES "honors_categories" ("honor_category_id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "master_honor_requirement_groups_master_honor_id_idx" ON "master_honor_requirement_groups" ("master_honor_id");
CREATE INDEX "master_honor_requirement_groups_honors_category_id_idx" ON "master_honor_requirement_groups" ("honors_category_id");

CREATE TABLE "master_honor_requirement_options" (
  "option_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" INTEGER NOT NULL,
  "label" VARCHAR(200) NOT NULL,
  "display_order" INTEGER NOT NULL DEFAULT 0,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

  CONSTRAINT "master_honor_requirement_options_pkey" PRIMARY KEY ("option_id"),
  CONSTRAINT "master_honor_requirement_options_group_id_fkey" FOREIGN KEY ("group_id")
    REFERENCES "master_honor_requirement_groups" ("group_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "master_honor_requirement_options_group_id_idx" ON "master_honor_requirement_options" ("group_id");

CREATE TABLE "master_honor_requirement_option_honors" (
  "option_honor_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "option_id" INTEGER NOT NULL,
  "honor_id" INTEGER NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

  CONSTRAINT "master_honor_requirement_option_honors_pkey" PRIMARY KEY ("option_honor_id"),
  CONSTRAINT "master_honor_requirement_option_honors_option_id_fkey" FOREIGN KEY ("option_id")
    REFERENCES "master_honor_requirement_options" ("option_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "master_honor_requirement_option_honors_honor_id_fkey" FOREIGN KEY ("honor_id")
    REFERENCES "honors" ("honor_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "master_honor_requirement_option_honors_option_id_honor_id_key"
    UNIQUE ("option_id", "honor_id")
);

CREATE INDEX "master_honor_requirement_option_honors_honor_id_idx" ON "master_honor_requirement_option_honors" ("honor_id");

CREATE TABLE "users_master_honors" (
  "user_master_honor_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID NOT NULL,
  "master_honor_id" INTEGER NOT NULL,
  "status" "user_master_honor_status_enum" NOT NULL,
  "awarded_at" TIMESTAMPTZ(6),
  "revoked_at" TIMESTAMPTZ(6),
  "recovered_at" TIMESTAMPTZ(6),
  "evaluated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "awarded_division_id" INTEGER,
  "source" "user_master_honor_source_enum" NOT NULL DEFAULT 'AUTO',
  "status_reason" "user_master_honor_status_reason_enum",
  "evaluation_snapshot" JSONB NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "modified_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),

  CONSTRAINT "users_master_honors_pkey" PRIMARY KEY ("user_master_honor_id"),
  CONSTRAINT "users_master_honors_user_id_fkey" FOREIGN KEY ("user_id")
    REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "users_master_honors_master_honor_id_fkey" FOREIGN KEY ("master_honor_id")
    REFERENCES "master_honors" ("master_honor_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "users_master_honors_awarded_division_id_fkey" FOREIGN KEY ("awarded_division_id")
    REFERENCES "divisions" ("division_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "users_master_honors_user_id_master_honor_id_key"
    UNIQUE ("user_id", "master_honor_id")
);

CREATE INDEX "users_master_honors_user_id_status_idx" ON "users_master_honors" ("user_id", "status");
CREATE INDEX "users_master_honors_master_honor_id_status_idx" ON "users_master_honors" ("master_honor_id", "status");

CREATE TABLE "master_honor_evaluation_history" (
  "history_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_master_honor_id" INTEGER NOT NULL,
  "user_id" UUID NOT NULL,
  "master_honor_id" INTEGER NOT NULL,
  "from_status" "user_master_honor_status_enum",
  "to_status" "user_master_honor_status_enum" NOT NULL,
  "reason" "user_master_honor_status_reason_enum",
  "evaluation_snapshot" JSONB NOT NULL,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "created_by_job_id" VARCHAR(100),

  CONSTRAINT "master_honor_evaluation_history_pkey" PRIMARY KEY ("history_id"),
  CONSTRAINT "master_honor_evaluation_history_user_master_honor_id_fkey" FOREIGN KEY ("user_master_honor_id")
    REFERENCES "users_master_honors" ("user_master_honor_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "master_honor_evaluation_history_user_id_fkey" FOREIGN KEY ("user_id")
    REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "master_honor_evaluation_history_master_honor_id_fkey" FOREIGN KEY ("master_honor_id")
    REFERENCES "master_honors" ("master_honor_id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "master_honor_evaluation_history_user_id_created_at_idx" ON "master_honor_evaluation_history" ("user_id", "created_at");
CREATE INDEX "master_honor_evaluation_history_master_honor_id_created_at_idx" ON "master_honor_evaluation_history" ("master_honor_id", "created_at");
