-- Migration: fix_rankings_nullable_category
--
-- Problem: award_category_id was nullable in club_annual_rankings, which
-- breaks the @@unique([club_enrollment_id, ecclesiastical_year_id,
-- award_category_id]) constraint in PostgreSQL because NULL != NULL.
-- Prisma upsert also does not accept NULL in compound unique where clauses,
-- requiring the unsafe `null as unknown as string` cast in application code.
--
-- Fix: make the column non-nullable with a sentinel UUID default
-- (00000000-0000-0000-0000-000000000000) that represents "general" rankings
-- (no specific award category).  The application code uses the exported
-- GENERAL_CATEGORY_ID constant to identify these records.
--
-- Steps:
-- 1. Ensure the sentinel UUID row exists in award_categories so the FK is
--    satisfied.  We insert it with ON CONFLICT DO NOTHING so re-running is
--    safe (idempotent).
-- 2. Update existing NULL values to the sentinel UUID.
-- 3. Drop the old unique constraint (which allowed NULLs).
-- 4. Alter the column to NOT NULL with a default.
-- 5. Re-create the unique constraint (now fully deterministic).

-- 1. Insert sentinel category record (idempotent)
INSERT INTO award_categories (
  award_category_id,
  name,
  description,
  club_type_id,
  min_points,
  max_points,
  icon,
  "order",
  active,
  created_at,
  modified_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'General',
  'Sentinel record — represents the overall (non-category-specific) ranking. Do not modify or delete.',
  NULL,
  0,
  NULL,
  NULL,
  0,
  false,  -- not shown in UI; purely a FK anchor
  NOW(),
  NOW()
) ON CONFLICT (award_category_id) DO NOTHING;

-- 2. Back-fill NULL award_category_id with sentinel UUID
UPDATE club_annual_rankings
SET award_category_id = '00000000-0000-0000-0000-000000000000'
WHERE award_category_id IS NULL;

-- 3. Drop old unique index/constraint (name generated by Prisma from field list)
--    The original was created via CREATE UNIQUE INDEX, not ADD CONSTRAINT,
--    so we must drop as INDEX first (shadow DB), then as CONSTRAINT (prod).
DROP INDEX IF EXISTS "club_annual_rankings_club_enrollment_id_ecclesiastical_year_id_award_category_id_key";
ALTER TABLE club_annual_rankings
  DROP CONSTRAINT IF EXISTS "club_annual_rankings_club_enrollment_id_ecclesiastical_year_id_award_category_id_key";

-- 4. Alter column to NOT NULL with sentinel default
ALTER TABLE club_annual_rankings
  ALTER COLUMN award_category_id SET NOT NULL,
  ALTER COLUMN award_category_id SET DEFAULT '00000000-0000-0000-0000-000000000000';

-- 5. Re-create unique constraint
ALTER TABLE club_annual_rankings
  ADD CONSTRAINT "club_annual_rankings_club_enrollment_id_ecclesiastical_year_id_award_category_id_key"
  UNIQUE (club_enrollment_id, ecclesiastical_year_id, award_category_id);
