import 'dotenv/config';
import fs from 'node:fs/promises';
import path from 'node:path';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

import {
  analyzeAdventurerSpecialtiesImport,
  applyAdventurerSpecialtiesImport,
  formatAdventurerSpecialtiesDryRunSummary,
  parseAdventurerSpecialtyAssetManifest,
} from '../src/honors/adventurer-specialties-importer';

const DEFAULT_DATASET_PATH = path.resolve(
  __dirname,
  '../../docs/working/aventureros-especialidades/index.csv',
);

function printUsage(): void {
  console.log(`
Usage:
  pnpm exec tsx scripts/import-adventurer-specialties.ts --dry-run [--dataset <path>]
  pnpm exec tsx scripts/import-adventurer-specialties.ts --apply --manifest <path> [--dataset <path>]

Environment:
  ADVENTURER_SPECIALTIES_IMPORT_DATABASE_URL  Optional. Overrides DATABASE_URL.
  DATABASE_URL                                Used when the override is not set.

Options:
  --dataset <path>  CSV source generated by the Adventurer specialties scraper.
  --manifest <path> JSON manifest with SACDIA-controlled imageUrl/materialUrl values.
  --dry-run         Validate and summarize the import without DB writes. Default.
  --apply           Persist Adventurer specialties idempotently. Requires --manifest.
  --help            Show this help.

Safety:
  - Default mode is dry-run.
  - Dry-run only reads club_types, classes and honors by code.
  - This script does not create, update or upsert records unless --apply is passed.
`);
}

function getArg(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function hasFlag(flag: string): boolean {
  return process.argv.includes(flag);
}

function createPrismaClient(): { prisma: PrismaClient; pool: Pool } {
  const databaseUrl =
    process.env.ADVENTURER_SPECIALTIES_IMPORT_DATABASE_URL ??
    process.env.DATABASE_URL;

  if (!databaseUrl) {
    throw new Error(
      'Missing DATABASE_URL or ADVENTURER_SPECIALTIES_IMPORT_DATABASE_URL',
    );
  }

  const pool = new Pool({ connectionString: databaseUrl });
  const adapter = new PrismaPg(pool);

  return {
    prisma: new PrismaClient({ adapter }),
    pool,
  };
}

async function main(): Promise<void> {
  if (hasFlag('--help') || hasFlag('-h')) {
    printUsage();
    return;
  }

  const apply = hasFlag('--apply');
  const datasetPath = path.resolve(getArg('--dataset') ?? DEFAULT_DATASET_PATH);
  const manifestPath = getArg('--manifest');

  if (apply && !manifestPath) {
    throw new Error('--manifest is required when using --apply');
  }

  const assetManifest = manifestPath
    ? parseAdventurerSpecialtyAssetManifest(
        JSON.parse(await fs.readFile(path.resolve(manifestPath), 'utf8')) as unknown,
      )
    : undefined;
  const { prisma, pool } = createPrismaClient();

  try {
    const result = await analyzeAdventurerSpecialtiesImport(prisma, {
      datasetPath,
      assetManifest,
      requireAssetManifest: apply,
      allowedAssetBaseUrls: apply
        ? {
            imageBaseUrls: [getRequiredEnv('R2_PUBLIC_URL_HONORS_IMAGES')],
            materialBaseUrls: [getRequiredEnv('R2_PUBLIC_URL_HONORS_PDF')],
          }
        : undefined,
    });

    console.log(formatAdventurerSpecialtiesDryRunSummary(result));

    if (result.warnings.length > 0) {
      console.log('\nWarnings:');
      for (const warning of result.warnings) {
        console.log(`- ${warning.message}`);
      }
    }

    if (result.errors.length > 0) {
      console.error('\nErrors:');
      for (const error of result.errors) {
        const location = error.rowNumber ? `row ${error.rowNumber}: ` : '';
        console.error(`- ${location}${error.message}`);
      }
      process.exitCode = 1;
      return;
    }

    if (apply) {
      const applyResult = await applyAdventurerSpecialtiesImport(prisma, {
        datasetPath,
        assetManifest: assetManifest!,
        requireAssetManifest: true,
        allowedAssetBaseUrls: {
          imageBaseUrls: [getRequiredEnv('R2_PUBLIC_URL_HONORS_IMAGES')],
          materialBaseUrls: [getRequiredEnv('R2_PUBLIC_URL_HONORS_PDF')],
        },
      });

      console.log('\nAdventurer specialties import apply result');
      console.log(`- honors created: ${applyResult.honorsCreated}`);
      console.log(`- honors updated: ${applyResult.honorsUpdated}`);
      console.log(
        `- honor club types upserted: ${applyResult.honorClubTypesUpserted}`,
      );
      console.log(`- class links upserted: ${applyResult.classLinksUpserted}`);
      console.log(
        `- requirements upserted: ${applyResult.requirementsUpserted}`,
      );
      console.log(
        `- requirements deactivated: ${applyResult.requirementsDeactivated}`,
      );
    }
  } finally {
    await prisma.$disconnect();
    await pool.end();
  }
}

function getRequiredEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} is required`);
  }
  return value;
}

main().catch((error) => {
  console.error('Adventurer specialties import failed:', error);
  process.exitCode = 1;
});
