import 'dotenv/config';
import fs from 'node:fs/promises';
import path from 'node:path';
import { ConfigService } from '@nestjs/config';

import { R2FileStorageService } from '../src/common/services/r2-file-storage.service';
import { StorageBucketAlias } from '../src/common/services/file-storage.service';
import {
  buildAdventurerSpecialtyAssetKeys,
  buildHonorCode,
  prepareAdventurerSpecialtiesDataset,
  resolveDatasetFilePath,
  type AdventurerSpecialtyAssetManifest,
} from '../src/honors/adventurer-specialties-importer';

const DEFAULT_DATASET_PATH = path.resolve(
  __dirname,
  '../../docs/working/aventureros-especialidades/index.csv',
);

function printUsage(): void {
  console.log(`
Usage:
  pnpm exec tsx scripts/upload-adventurer-specialty-assets.ts --dry-run [--dataset <path>]
  pnpm exec tsx scripts/upload-adventurer-specialty-assets.ts --apply --manifest-out <path> [--dataset <path>] [--overwrite]

Options:
  --dataset <path>      CSV source generated by the Adventurer specialties scraper.
  --manifest-out <path> Where to write the generated asset manifest after upload.
  --apply               Upload local assets to R2 and write the manifest.
  --dry-run             Validate local assets and print the upload plan. Default.
  --overwrite           Allow replacing existing R2 objects. Omit for safe first upload.
  --help                Show this help.

R2 strategy:
  - Images use existing HONORS_IMAGES config.
  - Materials use existing HONORS_PDF config.
  - No new buckets or env names are introduced.
  - Existing objects are reused safely unless --overwrite is passed.
  - Relative object keys:
      adventurers/images/{code}.png
      adventurers/materials/{code}.pdf
`);
}

function getArg(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function hasFlag(flag: string): boolean {
  return process.argv.includes(flag);
}

function createStorageService(): R2FileStorageService {
  const configService = {
    get: <T>(key: string): T | undefined => process.env[key] as T | undefined,
  } as ConfigService;

  return new R2FileStorageService(configService);
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  if (hasFlag('--help') || hasFlag('-h')) {
    printUsage();
    return;
  }

  const apply = hasFlag('--apply');
  const datasetPath = path.resolve(getArg('--dataset') ?? DEFAULT_DATASET_PATH);
  const manifestOutPath = getArg('--manifest-out');

  if (apply && !manifestOutPath) {
    throw new Error('--manifest-out is required when using --apply');
  }

  const prepared = await prepareAdventurerSpecialtiesDataset(datasetPath);
  const errors: string[] = prepared.validation.errors.map(
    (error) => error.message,
  );
  const uploadPlans = await Promise.all(
    prepared.rows.map(async (row) => {
      const code = buildHonorCode(row);
      const { imageKey, materialKey } = buildAdventurerSpecialtyAssetKeys(code);
      const imagePath = resolveDatasetFilePath(row.image, prepared.datasetRoot);
      const materialPath = row.pdf
        ? resolveDatasetFilePath(row.pdf, prepared.datasetRoot)
        : '';

      const imageExists = await fileExists(imagePath);
      const materialExists = materialPath
        ? await fileExists(materialPath)
        : false;

      if (!imageExists) {
        errors.push(`Missing local image for ${code}: ${imagePath}`);
      }

      if (!materialExists) {
        errors.push(
          `Missing local PDF material for ${code}: ${materialPath || '(empty pdf path)'}`,
        );
      }

      return {
        code,
        imagePath,
        materialPath,
        imageKey,
        materialKey,
        imageExists,
        materialExists,
      };
    }),
  );

  const imageReadyCount = uploadPlans.filter((plan) => plan.imageExists).length;
  const materialReadyCount = uploadPlans.filter(
    (plan) => plan.materialExists,
  ).length;

  console.log('Adventurer specialty asset upload plan');
  console.log(`- rows read: ${prepared.rows.length}`);
  console.log(`- images ready: ${imageReadyCount}`);
  console.log(`- PDF materials ready: ${materialReadyCount}`);
  console.log(`- missing assets: ${errors.length}`);
  console.log(
    `- target image key example: ${uploadPlans[0]?.imageKey ?? '(none)'}`,
  );
  console.log(
    `- target material key example: ${uploadPlans[0]?.materialKey ?? '(none)'}`,
  );

  if (errors.length > 0) {
    console.error('\nErrors:');
    for (const error of errors) {
      console.error(`- ${error}`);
    }
    process.exitCode = 1;
    return;
  }

  if (!apply) {
    console.log('\nDry-run only. Add --apply --manifest-out <path> to upload.');
    return;
  }

  const storage = createStorageService();
  const manifest: AdventurerSpecialtyAssetManifest = {};
  const overwrite = hasFlag('--overwrite');

  for (const [index, uploadPlan] of uploadPlans.entries()) {
    console.log(
      `[${index + 1}/${uploadPlans.length}] ${uploadPlan.code} — uploading/reusing assets`,
    );

    const imageResult = await uploadOrReuseObject({
      storage,
      bucketAlias: StorageBucketAlias.HONORS_IMAGES,
      key: uploadPlan.imageKey,
      filePath: uploadPlan.imagePath,
      contentType: 'image/png',
      overwrite,
    });
    const materialResult = await uploadOrReuseObject({
      storage,
      bucketAlias: StorageBucketAlias.HONORS_PDF,
      key: uploadPlan.materialKey,
      filePath: uploadPlan.materialPath,
      contentType: 'application/pdf',
      overwrite,
    });

    manifest[uploadPlan.code] = {
      imageUrl: imageResult.url,
      materialUrl: materialResult.url,
    };
  }

  await fs.writeFile(
    path.resolve(manifestOutPath!),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
  );

  console.log(`\nManifest written to ${path.resolve(manifestOutPath!)}`);
}

async function uploadOrReuseObject(args: {
  storage: R2FileStorageService;
  bucketAlias: StorageBucketAlias;
  key: string;
  filePath: string;
  contentType: string;
  overwrite: boolean;
}): Promise<{ url: string }> {
  const { storage, bucketAlias, key, filePath, contentType, overwrite } = args;

  if (!overwrite) {
    const existing = await storage.getObjectInfo(bucketAlias, key);
    if (existing) {
      return { url: storage.resolvePublicUrl(bucketAlias, key) };
    }
  }

  const buffer = await fs.readFile(filePath);
  return storage.upload(bucketAlias, key, buffer, {
    contentType,
    overwrite,
  });
}

main().catch((error) => {
  console.error('Adventurer specialty asset upload failed:', error);
  process.exitCode = 1;
});
