-- Especialidades de preparación ligadas a instancias de evento de camporee.
-- Spec: docs/superpowers/specs/2026-08-28-camporee-event-honors-design.md
-- Consultivo: no inscribe ni bloquea participación.

CREATE TABLE IF NOT EXISTS "camporee_event_honors" (
    "camporee_event_honor_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "camporee_event_id" INTEGER NOT NULL,
    "honor_id" INTEGER NOT NULL,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "camporee_event_honors_pkey" PRIMARY KEY ("camporee_event_honor_id"),
    CONSTRAINT "camporee_event_honors_event_honor_key" UNIQUE ("camporee_event_id", "honor_id"),
    CONSTRAINT "camporee_event_honors_camporee_event_id_fkey"
        FOREIGN KEY ("camporee_event_id") REFERENCES "camporee_events"("camporee_event_id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "camporee_event_honors_honor_id_fkey"
        FOREIGN KEY ("honor_id") REFERENCES "honors"("honor_id")
        ON DELETE RESTRICT ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_camporee_event_honors_honor"
    ON "camporee_event_honors"("honor_id");

CREATE INDEX IF NOT EXISTS "idx_camporee_event_honors_event_order"
    ON "camporee_event_honors"("camporee_event_id", "display_order");
